### ISSUE TITLE
Silents Gems Conflict

### ISSUE THREAD

**Issue by Tyrius1** [Thelnfamous1/Dungeons-Gear#10]
https://pastebin.com/A3VMHQCX
getting this when updating to latest version in 1.15.2
~Crash on launch~

forge - 31.2.45
Dungeons Gear - 1.15.2-1.2.0
Mixinboostrap - 1.0.5

**Comment by Thelnfamous1** [comment]
See #9. Astral Sorcery is currently incompatible with this mod in 1.15.

**Comment by Thelnfamous1** [comment]
Fixed in latest version.
