### ISSUE TITLE
[Suggestion] Enchantment chest loot Disable

### ISSUE THREAD

**Issue by Daejangnamu** [Thelnfamous1/Dungeons-Gear#100]
#Enable Enchantment in chest loot and trades. 
	#If you want to disable obtaining this mod's Enchantment disable this feature. [true / false]
	enableEnchantmentLoot = true
======================================

I want to disable all enchantment books.
option add please

**Comment by Thelnfamous1** [comment]
Will be added in next release, either by disabling enchantment trades or enchantments in loot.
