### ISSUE TITLE
Final Shout & Ice Wand

### ISSUE THREAD

**Issue by Mohrdain** [Thelnfamous1/Dungeons-Gear#102]
I have had two issues of crashes when Final Shout aims to trigger Ice Wand.  One crash apparently looked like I was shoved into a block and the second time the game just had an acception fault that caused my client to disconnect.  Please find the crash log attached along with the debug and log file for when I was disconnected.  This game is a modded SMP.

Thanks
[crash-2021-07-04_10.15.16-server.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/6764306/crash-2021-07-04_10.15.16-server.txt)
[debug.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/6764307/debug.log)
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/6764309/latest.log)

**Comment by Thelnfamous1** [comment]
Fixed in latest update already
