### ISSUE TITLE
Enchantment Incompatibility (even with config option active)

### ISSUE THREAD

**Issue by QuantumExp** [Thelnfamous1/Dungeons-Gear#104]
It seems that Sharpness/Smite/Bane of Arthropods are incompatible with Illager's Bane, even though the config option "enableOverpoweredEnchantmentCombos" is set to true. Other enchantments work fine (like Sharpness and Committed) but these ones just don't seem to be compatible. Is this intentional or is it a bug? If it's intentional, could you please make them compatible, for the sake of consistency?

**Comment by Thelnfamous1** [comment]
Seems like that’s Mojang’s intent for the vanilla sharpness-type enchants, to not be compatible with other sharpness-type enchants. I CAN make it so illager’s bane is not considered a damage enchantment.

**Comment by QuantumExp** [comment]
Please do. That would be very much appreciated. In my opinion, the whole idea of certain vanilla enchantments being incompatible with others is stupid, and should be removed. But that's just me.

**Comment by Thelnfamous1** [comment]
Will be fixed in next release
