### ISSUE TITLE
Advanced Config File Suggestion

### ISSUE THREAD

**Issue by BottomTextCf28** [Thelnfamous1/Dungeons-Gear#105]
Dungeons Gear is such a good mod, but it isn't necessarily balanced for every modpack or person's liking. I would like to suggest a more advanced config file with configuration for the following:

1. - Armor Durability & Damage Reduction Points - Some people might want armor to have more or less durability/armor bar points, and if this was configurable, it would help people a lot.

2. - Weapon Damage and Durability - Some people (including me) might find the damage of some of the weapons a bit too strong such as the claymore, bone club, anchors, and some bows. If we could edit the damage and durability, we could scale things up/down a bit, allowing for more balance.

3. - Item Disabling - A configuration file with all items and whether they spawn in chests or get traded by villagers that has a true/false statement on if the item is obtainable would be a great addition to have. With so many items, some people would rather disable an item than configure it, and for items such as artifacts, a disabling menu would be a very good tool, especially for modpack creators who might want certain items such as the totem of soul protection which could easily be abused, the currently bugged summoning items, and things that the developer or player just don't want in.

4. - This 4th one is less important, but it would also be nice if we could have a choice on where the dungeons gear is going. Some people might want it in specific mods, want to remove it from easy to find structures like ruined portals, or make it more of a challenge to get it, so a mod whitelist at the top and a vanilla loot table choose/remover would also be VERY helpful too.

Thank you SO much for considering, and I hope that with this possible change, Dungeons Gear could be a mod that's much more widely used and appreciated!

**Comment by BottomTextCf28** [comment]
> A part of the reason why these features haven’t been included yet is that there are hundreds of items and it would be laborious to make configuration options for each one. How do you propose the configuration should work for each of your requests in a satisfactory manner without there having to be the equivalent of an entire config file for each item?

Maybe it could be set into categories such as "big melee" "medium melee" and "small melee" for the damage configuration. For the disabling menu, the thing about every item having en/disabling was a bit outlandish on my part. You could have a disable menu where you typed in the item ID of the item you want to disable. The configuration about the loot tables could be done by just typing in the mod's ID in quotation marks. By default it should only be vanilla imo because if it gets added to When Dungeons Arise, for example, by default, there's no way of disabling it. I think it should be a list of enabled mods. The armors could also be grouped into the durability/armor point range. Same for bows as well.

**Comment by Patrigan** [comment]
As you may already be aware, but we have started moving to a datapack format. this will allow you to do everything you wanted and more. The latest beta shows several steps in that direction. Feel free to look at it and bring back any feedback you can, so we can improve before release.

**Comment by Patrigan** [comment]
Closing it, because I feel everything is present.
