### ISSUE TITLE
[FEATURE REQUEST] Config option for Souls vs XP

### ISSUE THREAD

**Issue by KyleHannon** [Thelnfamous1/Dungeons-Gear#106]
I love the new souls bar for that RPG quality, but would also love to be able to use the old method of XP in some modpack situations, for a lighter impact on vanilla gameplay. Would it be possible to include a config option to use either XP or Souls, for modpack customization?

**Comment by Thelnfamous1** [comment]
Tentatively going to say no to this, as we had to rip out the old XP system entirely and replace it with the new souls system. It’s kind if like asking Mojang to enable options for pre-1.8 combat vs what we have now in vanilla, it’s a bit too much work to make both of the incongruent systems work correctly.
