### ISSUE TITLE
[1.16.5-3.0.17] Lingering potion debuffs and damage do not applied to player

### ISSUE THREAD

**Issue by Ritzumi** [Thelnfamous1/Dungeons-Gear#107]
**Description**
Vanilla (and possibly modded lingering potions) do not damage or give debuffs to player. However, mobs still affected. This is tested when enableAreaOfEffectOnPlayers is true

**How to reproduce**
1. Join a world
2. Give a lingering potion of harming
3. Throw it on yourself

**Version**
Forge: 36.1.32
Dungeon gear: 3.0.17

No log or crash log file

Thank you~

**Comment by Thelnfamous1** [comment]
Will be fixed in next update
