### ISSUE TITLE
dungeons_gear-1.16.5-3.0.17  zh_cn.json

### ISSUE THREAD

**Issue by mcjyss** [Thelnfamous1/Dungeons-Gear#108]
[dungeons_gear-1.16.5-3.0.17——zh_cn.json.zip](https://github.com/Thelnfamous1/Dungeons-Gear/files/6830632/dungeons_gear-1.16.5-3.0.17.zh_cn.json.zip)

**Comment by Thelnfamous1** [comment]
@Jackiecrazy

**Comment by Patrigan** [comment]
Hi. With all the recent changes, this translation is now completely outdated :( A new beta will be going out real soon. If you could resubmit it at that point, I'll be sure to add it in!
