### ISSUE TITLE
Lucky Explorer enchant broken?

### ISSUE THREAD

**Issue by underscoren** [Thelnfamous1/Dungeons-Gear#109]
The description for the enchantment states "Chance to spawn emeralds with every block travelled", but it always spawns emeralds after travelling 6 blocks. The enchantment level only increases the amount of emeralds spawned.
This is obviously completely overpowered (especially with mods like Apotheosis which raise the max level for enchantments), and does not seem like the intentional behaviour.

**Comment by Thelnfamous1** [comment]
That is the intended behavior, the description which I ripped right from the official wiki admittedly doesn't make the 6 blocks rule clear. 

It is overpowered, which is why the enchantment is blacklisted by default for survival purposes.
