### ISSUE TITLE
the thundering enchantment/trait seems to be broken

### ISSUE THREAD

**Issue by aycfes** [Thelnfamous1/Dungeons-Gear#11]
well, hello github i've definently never been in and person i've never talked too

turns out hitting a mob (in this case a zombo with the lightning hammer crashes the game
[crash-2020-11-05_20.53.29-client.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/5497888/crash-2020-11-05_20.53.29-client.txt)
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5497889/latest.log)
[debug.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5497890/debug.log)

i recommend also testing the other ones, i'd do it myself, but can't rn

**Comment by Thelnfamous1** [comment]
Ah damnit, I can see why that would crash the game. This should only be the issue for the thundering enchant, as I am trying to spawn a visual-only lightning bolt on a successful thundering attack, but that may be exclusively server-sided. You can see this error when it says "ClientWorld cannot be casted to ServerWorld".

**Comment by Thelnfamous1** [comment]
This is an easy fix, an update should be released in the next few minutes, I'm just checking to see if there are any other foolish casts like that.

**Comment by aycfes** [comment]
you could use the particles like the ones from the staff
tho ya already got it figured out

**Comment by Thelnfamous1** [comment]
The staff and the thunder enchant actually share the same code for the "lightning blast" effect, combining the electric shock particles, visual-only lightning bolts and magic damage.

**Comment by Thelnfamous1** [comment]
I will be closing this issue for now, feel free to comment again if it somehow persists.
