### ISSUE TITLE
Crash with mod dark caverns

### ISSUE THREAD

**Issue by freerangerstudios** [Thelnfamous1/Dungeons-Gear#111]
Hey! Just tested my new mod with your mod dungeons gear and noticed that they are incompatible (crash on world load, stops at 100%). Here's the crash report: [https://pastebin.com/73Hxxkby](https://pastebin.com/73Hxxkby). The actual crash seems to happen on your side but I'm not really sure who's fault it his or really how to fix it at all. Would be nice if we could come up with a solution to allow the mods to be used alongside each other.

**Comment by Thelnfamous1** [comment]
Strange. Something has to be up with someone's implementation of getCapability.

This is my combo capability getter implementation:

```java
@Nonnull
    @Override
    public <T> LazyOptional<T> getCapability(@Nonnull Capability<T> cap, @Nullable Direction side) {
        return cap == COMBO_CAPABILITY ? instance.cast() : LazyOptional.empty();    
    }
```

This is yours:
```java
@Nonnull
    @Override
    public <T> LazyOptional<T> getCapability(@Nonnull Capability<T> cap, @Nullable Direction side) {
        return cooldownOptional.cast();
    }
```

**Comment by Jackiecrazy** [comment]
@freerangerstudios directly casting does not check whether the capability is actually an instance of your capability. I write mine like so:
`
@Nonnull
    @Override
    public <T> LazyOptional<T> getCapability(@Nonnull Capability<T> cap, @Nullable Direction side) {
        return CAP.orEmpty(cap, instance);
    }
`
This is identical to Infamous' implementation, except forge innately provides the comparison.

**Comment by freerangerstudios** [comment]
Thanks for the help! Uploading a hotfix now that'll fix the compatibility issues.
