### ISSUE TITLE
Lightning rod

### ISSUE THREAD

**Issue by holyaurora21** [Thelnfamous1/Dungeons-Gear#113]
my partner used the lighting rod from dungeon gear and now it wont stop doing lightning strikes when jumping...  tried re-log and also killing him but still keeps doing lightning every time he jumps

**Comment by holyaurora21** [comment]
ps this issue is on a modpack 
Medieval minecraft

**Comment by Thelnfamous1** [comment]
Does he have the Electrified enchantment on any of his armor?

**Comment by holyaurora21** [comment]
Nope. He had the ender golem armour (farlands). Did ask him to check if he got any weird curses or enchants after using it but everything was how it should of been.......unless it did not show the enchant correctly

**Comment by Thelnfamous1** [comment]
Does it happen when using the mod by itself? Sounds like a very strange mod interaction - logs might be helpful here.

**Comment by holyaurora21** [comment]
no idea since im using a modpack.
can't do logs since its not my server 👎

**Comment by Patrigan** [comment]
Lightning rod has gotten some changes in the latest alpha and beta builds. Feel free to check if it still happens locally. I made double sure it has nothing to do anymore with jumping.
