### ISSUE TITLE
Dungeon Gears does not use the loot table from the context when generating loot

### ISSUE THREAD

**Issue by TelepathicGrunt** [Thelnfamous1/Dungeons-Gear#114]
Hello! I gotten a report on my mod Repurposed Structures about my mod no longer importing Dungeon Gear's modded loot from vanilla loot tables. 
https://github.com/TelepathicGrunt/RepurposedStructures/issues/121

After looking closely and debugging, I found the reason why rolling vanilla's loot tables in my GLM does not spawn Dungeons Gear's loot is because Dungeon Gear is checking the loot table of the block directly. 
![image](https://user-images.githubusercontent.com/40846040/127770307-a049687c-0e8e-43ef-a120-53d53f4b45b4.png)

You actually do not need to do that at all. The loot table to spawn is already in the `LootContext context` parameter and can be grabbed by doing `context.getQueriedLootTableId()`. If you switch to using that, it'll help simplify your code a bit and make my mod's modded loot importing work again with Dungeon Gears. It may also help with compat for other mods that tries to roll loot table loot outside of chests to try and analyze the loot outputs or something unique or wacky.

**Comment by TelepathicGrunt** [comment]
This is my code I do for rolling vanilla loot tables
https://github.com/TelepathicGrunt/RepurposedStructures/blob/f435358cda49a3f5743fab9769ed0dca5b1671db/src/main/java/com/telepathicgrunt/repurposedstructures/misc/StructureModdedLootImporter.java#L159-L160

This is the Dungeons Gear part that is grabbing my chest's loot table instead of using the passed in loot table in context. 
https://github.com/Thelnfamous1/Dungeons-Gear/blob/117c4db96bacb42ae0a454b329287297f43c52c4/src/main/java/com/infamous/dungeons_gear/loot/GlobalLootModifier.java#L202-L222

**Comment by Thelnfamous1** [comment]
This is because the loot table id in context wasn’t a thing in the version of forge this mod was compiled against. Will need to update my Forge version to latest to get this fixed.

**Comment by TelepathicGrunt** [comment]
Ah. That makes sense! Yeah the new context stuff is super useful

**Comment by Patrigan** [comment]
Fix has been implemented and should come in a future version.

**Comment by Patrigan** [comment]
Fix available in 3.0.21
