### ISSUE TITLE
config durability edits not working on server. 

### ISSUE THREAD

**Issue by ArMoReDfUrY** [Thelnfamous1/Dungeons-Gear#118]
forge 1.16.5-36.2.2

config changes made to weapon durability are not being registered on my server.
i brought melee weapon durability up to 450 but in game it is still the default 250, same result for bows, crossbows & artifacts.
i have not edited armour durability so i'm unsure if it's working or not.
i have not tested this on a SP world either.

**Comment by Patrigan** [comment]
We are currently rewriting the way durability (and all other stats) work. This should be resolved as soon as we resolve #105 . Closing this ticket for now, please watch the other ticket.
