### ISSUE TITLE
Vanilla converted diamond tools and weapons are undesirable due to durability loss.

### ISSUE THREAD

**Issue by ArMoReDfUrY** [Thelnfamous1/Dungeons-Gear#119]
There is currently no good reason to convert to dungeons gear versions of diamond items as they take a massive durability decrease. 

Take the diamond sword as example, you need to use 1 diamond to convert it, gaining sharpness I is a fair trade for the additional cost but losing 1311 points of durability unfortunately makes this conversion worthless to do.

if you bring the converted diamond tools & weapons up to their original vanilla durability levels it would make the conversions worth the additional resources and a more compelling choice.

additionally the conversions for the gold axe/sword & the stone sword give too much durability , gold being 32 & stone 131 points in vanilla.

iron is the only balanced items being on par with vanilla at 250 points.

**Comment by Patrigan** [comment]
I suggest watchign #105 . It won't directly fix this issue, but it will allow you to make corrections yourself so that the durability is where you want it. Be aware, for now, there is no intention to actually replace the vanilla diamond tools.
