### ISSUE TITLE
1.16.1-1.2.0 crash on startup

### ISSUE THREAD

**Issue by LifelessSaint** [Thelnfamous1/Dungeons-Gear#12]
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5498730/latest.log)

**Comment by Thelnfamous1** [comment]
I need complete logs. the entire latest.log, as well as debug.log and and a crash report log if available.

**Comment by LifelessSaint** [comment]
[debug.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5498789/debug.log)
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5498790/latest.log)   is this the entire thing? 

It doesn't generate a crash report log for some reason.

**Comment by Thelnfamous1** [comment]
I can find no reference to any error from my mod in these 2 new logs you posted. How did you get the first log you posted above?

**Comment by LifelessSaint** [comment]
I'm really not sure why those were different. I had pulled them from the /log folder... 
I cleared it and generated new ones. Here they are. 
[debug.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5498933/debug.log)
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5498935/latest.log)

**Comment by LifelessSaint** [comment]
I'm not sure why it doesn't generate a full "latest" log

**Comment by Thelnfamous1** [comment]
The issue still appears to be the same. Something is causing my mixin for the player to allow them to attack beyond standard attack reach to fail.

**Comment by nosciencehere** [comment]
Hey I'm getting a crash on boot too. Tried to run a clean instance with only Dungeons Gear (and JEI) and the game freezes while on the red loading screen.

On Forge 32.0.108
V 1.16.1

Attaching both debug.log and latest.log from the clean run, hopefully this helps.
[debug.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5502307/debug.log)
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5502308/latest.log)

**Comment by aycfes** [comment]
this seems to be the same, or a similar problem to the one in the latest(major) 1.15 version, to my untrained eye, what other mods do y'all have installed?
and if any of them do anything with reach, try removing them and then booting the game

**Comment by Thelnfamous1** [comment]
Just found the issue guys, will be uploading a fix right now

**Comment by Thelnfamous1** [comment]
It's up now guys, let me know if this error persists

**Comment by Thelnfamous1** [comment]
Still getting reports of the error persisting, reopening and working on a fix now

**Comment by Thelnfamous1** [comment]
So there wasn't anything specifically wrong in the code, it turns out the jars I was building were just not including updated reference maps for the mixin for whatever reason. It was still using the old ones from before the big update. I just kind of "cleared the cache" and boom, everything that needed to be in there was finally there. Re-uploaded 1.2.0 for 1.16.1, should be good to go now. Again, if this is somehow still persisting, feel free to reply again.
