### ISSUE TITLE
Weakening Enchantment doesn't apply to the attacked mob

### ISSUE THREAD

**Issue by RecyclingTiger** [Thelnfamous1/Dungeons-Gear#125]
When I hit a mob, they don't get the weakness effect (no particles) and their attack damage attribute does not change.

tested with /attribute @e[limit=1,sort=nearest,type=!player] minecraft:generic.attack_damage get

**Comment by RecyclingTiger** [comment]
after further testing, it seems to affect every mob nearby **EXCEPT** the mob you are attacking, so I have changed the title.

**Comment by Patrigan** [comment]
Fixed
