### ISSUE TITLE
Powershaker Kills Other Mobs In Two Hits

### ISSUE THREAD

**Issue by Tinn04** [Thelnfamous1/Dungeons-Gear#126]
I used the Powershaker and was able to the redstone golem in 2-3 hits. I tried this out with other mobs from other mobs and the result is the same. It seems like the Powershaker does 50% percent of a mob's health. Not sure if this is intended but it is quite overpowered.

**Comment by Patrigan** [comment]
This will be fixed in the upcoming alpha 3.1.11. Reminder alpha versions are timed-exclusive to Patreons. After a short while, a beta will be released to CurseForge.
