### ISSUE TITLE
Add Leggings and Boots as Cosmetics or Functional Armor?

### ISSUE THREAD

**Issue by Innomenatus** [Thelnfamous1/Dungeons-Gear#127]
I know this sounds quite heretical or redundant, but armor in Minecraft Dungeons often include leggings and boots, even if they are cosmetic. I just want to add leggings and boots to some mobs to make them appear more complete.

Forgive me if they are already added, I checked the mod folders poorly if they were there.

**Comment by Patrigan** [comment]
This feature is planned for our 1.18.2 releases. Sadly this is still a short while away, so hang tight!

**Comment by Innomenatus** [comment]
Huh, that's neat.

It's quite the coincidence that the one time I checked on GitHub to see if my question was answered, it was answered the day before. What a pleasant surprise! Thanks for your hard work!

**Comment by Patrigan** [comment]
We have now released this in 1.16.5. We got this request far too often. Check our latest beta version to enjoy them!
