### ISSUE TITLE
Server Crash on Forge 36.1.0 Exception Ticking World

### ISSUE THREAD

**Issue by Nikowsky132** [Thelnfamous1/Dungeons-Gear#129]
Hi, I'm really new to this, I don't even know if I'm in the right place to ask for help...  recently I have encountered crashes on my Exaroton server, I have 150 mods installed, and apparently there hasn't been incompatibility issues among them, so I don't think it has something to do with that, but the thing is, the server is now crashing everytime I enter my world and stay for 20 secods aprox. I'm on a place next to a Pirate ship (a building) from another mod, that has pillagers and pillager spawners in it, I try to escape but the server crashes and leaves me with this message on the console: 

<html>
<body>

[18Sep2021 00:31:30.583] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 3e27030e-2e9d-4a0a-837f-cebf17db6b4f
--
3855 | [18Sep2021 00:31:30.586] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
3856 | net.minecraft.crash.ReportedException: Exception ticking world
3857 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
3858 | at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
3859 | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
3860 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
3861 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
3862 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
3863 | Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.projectile.ProjectileHelper.getWeaponHoldingHand(Lnet/minecraft/entity/LivingEntity;Ljava/util/function/Predicate;)Lnet/minecraft/util/Hand;
3864 | at com.infamous.dungeons_mobs.entities.water.SunkenSkeletonEntity.func_85036_m(SunkenSkeletonEntity.java:166) ~[dungeons_mobs:1.0.10]
3865 | at net.minecraft.entity.monster.AbstractSkeletonEntity.func_184201_a(AbstractSkeletonEntity.java:203) ~[?:?]
3866 | at com.infamous.dungeons_mobs.entities.water.SunkenSkeletonEntity.func_180481_a(SunkenSkeletonEntity.java:192) ~[dungeons_mobs:1.0.10]
3867 | at net.minecraft.entity.monster.AbstractSkeletonEntity.func_213386_a(AbstractSkeletonEntity.java:136) ~[?:?]
3868 | at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:175) ~[?:?]
3869 | at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?]
3870 | at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?]
3871 | at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:359) ~[?:?]
3872 | at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292]
3873 | at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?]
3874 | at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?]
3875 | at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?]
3876 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
3877 | ... 5 more

</body>
</html>

I read an article that gave me a solution for the Exception ticking world error, and that was to enter the forge.cfg file and set "removeErrorEntities" to true, but it didn't help... I don't know what else to do, my server has 9 GB of RAM avalaible and I don't think the issue has something to do with the RAM... 

I gently hask if you can help me, I will provide more information if needed, I don't know what else to add here so... thank you in advance :')

**Comment by Patrigan** [comment]
This is actually a dungeons Mobs issue. It has since been reported there. Please keep an eye on the following url:
https://github.com/Thelnfamous1/Dungeons-Mobs/issues/58

Closing here now.
