### ISSUE TITLE
Mixin Crash w/ Resourceful Bees

### ISSUE THREAD

**Issue by WenXin20** [Thelnfamous1/Dungeons-Gear#13]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Dungeons' Gear v1.2.2`
[`Resourceful Bees v0.3.8a`](https://www.curseforge.com/minecraft/mc-mods/resourceful-bees)

I started getting this crash with mixin after installing the Resourceful Bees mod.
[Error Log](https://gist.github.com/WenXin20/f8dd29ab54601b7267332bc3302add80)

**Comment by Thelnfamous1** [comment]
See #7. This is up to Resourceful Bees to fix.

**Comment by WenXin20** [comment]
Ok, thanks.
