### ISSUE TITLE
[Enhancement] Add config option to disable compat with Dungeon Mobs mod

### ISSUE THREAD

**Issue by binartelier** [Thelnfamous1/Dungeons-Gear#130]
Thank you for your effort porting all these amazing weapons from mc dungeon, really appreciated it.

However, i do have a simple request. Can we get an option to disable armored mob of using dungeon gear armors? I'm currently trying to use this mod with Epic Fights but well, there is the well-known incompatibilities. I've disabled armor loot tables already, but noticed that the armored mobs are still using the armors regardless.

**Comment by Patrigan** [comment]
This should be added to Dungeons Mobs, as that's the mod introducing the compat. Can you remake the issue there?
