### ISSUE TITLE
Other dungeons have no gears

### ISSUE THREAD

**Issue by JiuyeAyan** [Thelnfamous1/Dungeons-Gear#131]
I love this mod, it's so cool.

But it seems doesn't support Dungeons Arise and Eternal Tales, chests on these dungeons mods have no any gear items.

Are there any possibility to handle this?

**Comment by Patrigan** [comment]
Currently, there is a config option to add loot to specific tables.
commonLootTables, uncommonLootTables and rareLootTables.
Adding the loottable for their chests to these lists will make the loot pop up in those chests.
