### ISSUE TITLE
Problem with graphics/mod

### ISSUE THREAD

**Issue by MoRgAn005** [Thelnfamous1/Dungeons-Gear#134]
Hello. I recently ran into a problem in the Dungeons gears mod. The problem is this: when you launch the world with this mod, the graphics in minecraft become pixelated at a distance. I tried to run this mod with and without an optifine, removed other mods, but the problem remained unchanged

**Comment by Patrigan** [comment]
Could you confirm these problems still exist in latest beta?
I have thus far received no other reports on this.

**Comment by Patrigan** [comment]
After spending some time investigating this, I have been unable to confirm this issue. For any armor rendering, I would suggest checking if you use Epic Fight Mod, that's a very annoying mod that messes up armor rendering a lot.
