### ISSUE TITLE
Mahou tsukai incompat ?

### ISSUE THREAD

**Issue by LeKripiY** [Thelnfamous1/Dungeons-Gear#136]
Hey i'm aplaying a modpack with friends and on this modpack we have the mahou tsukai mod installed as well as the dungeon gears mod. There is a bug where i can't damage my tamed wolf (wich i need for mahou tsukai) and i reported this issue on reddit, a mahou tsukai dev told me that it might be the dungeon gear mod that is turing off friendly fire for pets and it might be turned back on in the config but i can't find anything about friendly fire on pets.

**Comment by Patrigan** [comment]
Issue has been resolved in latest version: 3.0.21
