### ISSUE TITLE
Crash client after update 3.0.20

### ISSUE THREAD

**Issue by fullshadow** [Thelnfamous1/Dungeons-Gear#138]
After upgrading to version 3.0.20 Interacting with TotemOfHolding from QuarkOddities mod causes the client to crash
[crash-2021-11-06_21.29.09-client.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/7491063/crash-2021-11-06_21.29.09-client.txt)
.

**Comment by Jackiecrazy** [comment]
This has been fixed by the hotfix. Sorry for the inconvenience!
