### ISSUE TITLE
Items not working

### ISSUE THREAD

**Issue by nengoxx** [Thelnfamous1/Dungeons-Gear#14]
hi, I'm using the latest version of the mod for minecraft 1.16.3 and some items don't seem to be working, specifically the quivers and the corrupted seeds, they trigger the cooldown but in the case of the quivers they don't give anything and corrupted seeds doesn't seem to do anything to enemies either. Great mod btw.

**Comment by Thelnfamous1** [comment]
The flaming quiver, when you activate it, makes the next 7 arrows you shoot flaming arrows. 

The torment quiver, when you activate it, makes the next 3 arrows you shoot "torment" arrows that are no-clip, have no gravity, fly slowly and deal high knockback. 

The corrupted seeds inflict poison on enemies within a few block of you.

**Comment by nengoxx** [comment]
oh, that might be it then, thanks for the clarification.
