### ISSUE TITLE
Entity cannot be cast to LivingEntity

### ISSUE THREAD

**Issue by PickleGaming32** [Thelnfamous1/Dungeons-Gear#141]
Whenever hitting/trying to destroy entities like boats or firecharges spawned from ghasts game crashes with the following crash report
[crash-2021-11-12_16.56.18-client.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/7532848/crash-2021-11-12_16.56.18-client.txt)

Cheers, great mod btw.

**Comment by Jackiecrazy** [comment]
This was fixed in the hotfix, please update the mod to resolve this issue.
