### ISSUE TITLE
After using Poison Cloud, the player becomes permanently immune to the poison effect.

### ISSUE THREAD

**Issue by RecyclingTiger** [Thelnfamous1/Dungeons-Gear#148]
Specifically the poisonImmunityTimer tag gets stuck at 60 ticks after using the Poison Cloud enchantment (melee or ranged) meaning you are permanently immune to poison until next death.

Issue exists in 1.16.5-3.1.0-hotfix, 3.1.0-beta, 3.1.1-beta, and 3.1.2 beta.

**Comment by Patrigan** [comment]
Fixed in 3.1.11-alpha
