### ISSUE TITLE
Newest 1.16.1 version: unable to open loot chests

### ISSUE THREAD

**Issue by fnquantum** [Thelnfamous1/Dungeons-Gear#15]
This issue doesn't exist on the previous 1.16.1 release of the mod.
Newest mod update for 1.16.1 makes it so that chests with generated loot cannot be opened.
Breaking the chest only drops the chest itself.
Issue with loot generation??

**Comment by Thelnfamous1** [comment]
I need logs

**Comment by fnquantum** [comment]
I'm not sure how I'm supposed to log something that's simply an in-game mechanical issue.
The game doesn't crash or anything, the chests just won't open.

**Comment by Thelnfamous1** [comment]
The latest.log should definitely have some kind of error when you open the chest in-game

**Comment by Thelnfamous1** [comment]
Oh, I think I found the problem man. I forgot that in 1.16.2, the chest loot code is slightly different than in 1.16.1, so when I copied over all the updated stuff from 1.16.2+ to 1.16.1 that I should've changed that code to line up with the 1.16.1 version. Thanks for letting me know about this, I will fix it now and upload a new version for 1.16.1.

**Comment by Thelnfamous1** [comment]
For future reference, this is what the latest.log will tell you about a situation like this:

https://pastebin.com/rGsTDyic

**Comment by Thelnfamous1** [comment]
Latest version fixes this issue.
