### ISSUE TITLE
Dedicated server crash

### ISSUE THREAD

**Issue by ChromaPIE** [Thelnfamous1/Dungeons-Gear#150]
Crash report: https://www.toptal.com/developers/hastebin/zuwamipaso.rb

**Comment by DoctorMage** [comment]
Another instance of server not starting up after updating dungeon gears
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/8306951/latest.log)

**Comment by Patrigan** [comment]
We are aware of the issue and intend to release a fix tomorrow.

**Comment by Patrigan** [comment]
Fixed in 3.1.9-beta
