### ISSUE TITLE
Game breaking Bug found

### ISSUE THREAD

**Issue by LavaCatPlayz** [Thelnfamous1/Dungeons-Gear#151]
I found out that using the swap item with off-hand keybind or just dragging the item from offhand into the 2x2 crafting area you can combine two dual-wield items (Gauntlets, Daggers, etc) and craft a new unenchanted version for free also allowing you to combine durability. Than you can also enchant this item for free if you use the keybind to put the enchanted version in the second anvil slot and put the new unenchanted item in the first slot and combine them thus allowing you to duplicate any dual-wield items and enchant them for free. I duplicated and enchanted the gauntlets as an example in the image, this is a modpack so you might not recognize the enchantments but the point is you can duplicate items and also duplicate the enchantments.
![image](https://user-images.githubusercontent.com/69319607/158910953-ae7110f1-fa63-43c5-83f1-1e7e07f36e08.png)
![image](https://user-images.githubusercontent.com/69319607/158910963-c99760be-28e4-46d8-888d-b30d75f7b74d.png)

**Comment by Patrigan** [comment]
Due to the various issues, Dual Wield items have now been moved to Experimental, pending a complete reimplementation. Experimental will be added in the next beta release.
