### ISSUE TITLE
Enchantment config prevents enchanting melee dungeonsgear items

### ISSUE THREAD

**Issue by VanyaBaou** [Thelnfamous1/Dungeons-Gear#153]
Minecraft Version: 1.16.5
Forge Version: 1.16.5-forge-36.2.23
Dungeons Gear Version: dungeons_gear-1.16.5-3.1.9-beta

With **enableEnchantsOnNonDungeonsGear** set to **false**, you can't apply any dungeonsgear enchants onto melee items _at all_.

**MELEE** enchants can't apply to _anything_
**MELEE_RANGED** can still apply to ranged dungeonsgear items
Every other enchant is functioning correctly

**Comment by Patrigan** [comment]
This will be fixed in 3.1.14-beta

**Comment by VanyaBaou** [comment]
Issue still happening on newest version
Many enchants can't apply to any items

**Comment by Patrigan** [comment]
Will be fixed in 3.2.2.

**Comment by Patrigan** [comment]
fixed
