### ISSUE TITLE
Dual wielding weapons' compat problem with Inventorio

### ISSUE THREAD

**Issue by ChromaPIE** [Thelnfamous1/Dungeons-Gear#154]
Inventorio provides four off-hand toolbelt slots, replacing the vanilla offhand slot, for players to switch items in the offhand among them. But due to some reasons it's quite broken and confusing with dual wielding weapons in Dungeon's Gear because it "ghost-transmutates" and "ghost-dupes" items. For ghost I mean all these glitches are visual, you can't actually void or dupe anything with the glitch. Well, I don't know how to describe it. Forgive me.

Steps to reproduce:
1. Install Inventorio and DGear, grab a pair of dual weapons
2. Equip them
3. Scroll the wheel to another slot
4. The offhand one doesn't unload, visually. If you try to take it out of the slot it will disappear.
5. (ghost-duping) With the newly selected slot being empty, press the key to swap hands, F by default. Here comes the dupe in the mainhand, visually. You can even throw it out but it will vanish by the time you pick it up.
5. (ghost-transmumating) With the newly selected slot containing items, pressing F will visually replace that item with the weapon. Your item will now be held in offhand, but with a facade of that dual wielding weapon.

Please let me know if it's actually Inventorio's side. But as the dual wielding gameplay was introduced by DGear, I chose to report it here first.

**Comment by Patrigan** [comment]
Due to the various issues, Dual Wield items have now been moved to Experimental, pending a complete reimplementation. Experimental will be added in the next beta release.
