### ISSUE TITLE
Souls

### ISSUE THREAD

**Issue by tronnyg** [Thelnfamous1/Dungeons-Gear#155]
Hi is it possible to keep souls upon death and maybe change how many souls killing a certain mob give you?

**Comment by Patrigan** [comment]
Based on your feedback, I made keeping souls upon death will be a config option in the next version. Still disabled by default, but you'll be able to change that. Kepe youre eyes open for the next beta version!

Different amount of souls, however, is not what it is currently balanced towards. Also wouldn't really make logical sense, I suppose xD More problematically, I'm not sure how I can make that configurable in an approachable way.
