### ISSUE TITLE
Maybe a potential bug of new armor.

### ISSUE THREAD

**Issue by rtxyd** [Thelnfamous1/Dungeons-Gear#156]
<item:dungeons_gear:emerald_chestplate> and <item:dungeons_gear:opulent_chestplate> and <item:dungeons_gear:gilded_glory_chestplate> and <item:dungeons_gear:opulent_helmet> and <item:dungeons_gear:emerald_helmet> trigger some hidden mechanic of the mod "touhoulittlemaid". When I equip one of above and move toward any directions, it keeps spawning one item of "touhoulittlemaid".

**Comment by Patrigan** [comment]
Hmmm, they're dropping emeralds as you walk around, based on a loot table. Possibly that mod overrides emeralds?

**Comment by Patrigan** [comment]
Confirmed. Touhoulittlemaid is replacing dropped emerals with another item. You can adjust the loottable for Lucky Explorer to change what it drops in a modpack with both mods.
