### ISSUE TITLE
Shields don't block arrows

### ISSUE THREAD

**Issue by RaindeerGamez** [Thelnfamous1/Dungeons-Gear#159]
When I try to block an arrow using a shield (modded or vanilla) in version 3.1.14 I still take the arrow damage. Shields still work against melee attacks though. The issue went away when downgraded back to 3.1.9.

**Comment by Patrigan** [comment]
Not even shields from vanilla block arrows? With which bow is the arrow shot?

**Comment by RaindeerGamez** [comment]
Yeah vanilla shields were no different. The bows used were vanilla bows used by vanilla skeletons. It was the same with other bow-wielding mobs. I haven't tested whether or not it's the case with all projectiles yet

**Comment by people04** [comment]
I think I know how fix this problem but I am animating enderman

**Comment by people04** [comment]
Because this mod add damage value when players was damage

**Comment by people04** [comment]
Your shield block vanilla arrow damage but cannot block mod added damage value

**Comment by people04** [comment]
😀

**Comment by people04** [comment]
Fix it will not hard

**Comment by people04** [comment]
If this haven't fixed. You can think of arrow as too much force you can not use shield to block it

**Comment by XiFengXF** [comment]
In the case of only adding this mod, the damage of the monster's long-range arrows will pass through the shield;  adding other creature mods, the arrows shot by other monsters do the same; so this problem seriously affects the game.

**Comment by Patrigan** [comment]
So the error as a bit more special and also more annoying. All arrows were Harpoon Arrows, apparently... THey have an additional pierce level and thus pass a shield at least once.

Bug is fixed in the next Beta Version.
