### ISSUE TITLE
[MC1.15.2V1.2.2]Client Crash on Server when returning from Main Menu

### ISSUE THREAD

**Issue by KajesLorian** [Thelnfamous1/Dungeons-Gear#16]
https://pastebin.com/nPtkCWfK

Steps to reproduce
Add to server
Add to Client
Join Server
Press "Escape" key to go to main menu
Press "Back to Game" Button, Client crashes

(Client does not crash if you use the "Escape" button to return to world)

**Comment by Thelnfamous1** [comment]
This is certainly strange. The way I handle long reach attacks in 1.15.2 may be the issue here, as I am looking for left click input to determine if an extended reach attack was successful. I never accounted for the fact that it may be looking for it while the game is paused.

**Comment by Thelnfamous1** [comment]
Try this on the latest version for 1.15.2. I have added a null check for the attribute, hopefully that should resolve this issue.
