### ISSUE TITLE
Gear is missing tags (1.16.5)

### ISSUE THREAD

**Issue by EmoBubbleGum** [Thelnfamous1/Dungeons-Gear#161]
![javaw_djcUmFef8m](https://user-images.githubusercontent.com/24841270/179133761-05eec506-2a61-4be0-9189-afe0fd2eb935.png)

The gear doesn't have "#forge:weapons" or "#forge:armor" in the NBT tags, which I am assuming is why apotheosis affixes cannot be applied to them. Pic below is a pike from Spartan Weaponry, which works fine with affixes.

![javaw_j7NuhkG9yS](https://user-images.githubusercontent.com/24841270/179134146-a4cc3158-cdc2-4ae7-a0f4-439aeb5ae472.png)
.

**Comment by Patrigan** [comment]
Will add them. Did not know this was a thing :O

**Comment by EmoBubbleGum** [comment]
A quick addendum; the armor seems to work with the affixes, and I am not sure if armor requires any tags in general, as I don't see armor with an equivalent of a "forge:weapons" tag. Either way hoping this ends up being a simple fix, and is indeed only an issue with those tags.

**Comment by Patrigan** [comment]
I have added the tags. I have not tested Spartan Weaponry. When the new beta version releases, let me know with a new issue if it doesn't work yet.
