### ISSUE TITLE
Bugs in 3.1.14

### ISSUE THREAD

**Issue by tronnyg** [Thelnfamous1/Dungeons-Gear#162]
There are a couple of bugs in this update that make the game unplayable. Ive downgraded to 3.1.9 and everything works fine so ill use that for now but just making sure everyone is aware of these bugs.

1 - Some weapons do little to no damage
2 - Unlike 3.1.9 in 3.1.14 if you are using the epic fight mod each weapon needs to be added as custom weapons in the config file
3 - Artifacts don't work by holding & right clicking anymore you need to add them in the curious slot and if you try to use them like that the game crashes (mainly just the ones that use souls others work fine)
4 - Certain weapons with enchantments such as freeze etc. still deals damage but the enchantments dont work

**Comment by Patrigan** [comment]
1 - Already being tracked in #160
2 - I am afraid this won't be able to change. Several changes in the way the weapons work make them unique. Sorry for the additional config work!
3 - Yes, this is intended. Curios is now the goto way, as some add stuff that you only get when you have them equipped, primarily the soul ones that give you additional soul collection. I haven't seen any issue with the soul ones. Could you add a crash log?
4 - This one is new. I quickly verified and I can see the effects being applied. I did notice an issue with Freezing in particular where the effect had an amplifier of 0 (effect but with no strength) and already fixed that for the next beta. A quick check showed me no other enchants with the issue.

All that is left is number 3. If you can provide me crash log I can look into it.

**Comment by tronnyg** [comment]
Ok cool np. With no.3 artifacts dont crash the game anymore i think i was a error with another mod. The only thing is that when using the corrupted pumpkin/beacon the beam shoots out but im unable to stop it.

**Comment by Patrigan** [comment]
THis has been fixed in 0.0.17-beta. Thank you for being so patient!
