### ISSUE TITLE
Weapons still can't recieve apotheosis affixes.

### ISSUE THREAD

**Issue by EmoBubbleGum** [Thelnfamous1/Dungeons-Gear#164]
![javaw_i5zIiqTYCV](https://user-images.githubusercontent.com/24841270/180869347-fc250df6-7854-4f62-a91b-7b58cd0c25f4.png)
![javaw_6wngHw8fgd](https://user-images.githubusercontent.com/24841270/180869350-a943649d-de4a-457b-a260-66920d1e4ad1.png)

Not sure if it is a tagging issue, especially since I don't know how the tags are integrated. For example the vanilla swords don't even have a weapons tag, but they still work tagged as a sword. Meanwhile the polearms from other mods are simply 'weapons', like the one in the image, and work fine with affixes.

**Comment by Patrigan** [comment]
Out of curiosity, which mod shows you that information. I think I need it in my dev environment ...

**Comment by Patrigan** [comment]
So I went in depth this time. We'll need to make a complete datapack for it.

I will get on that and maybe have a chat with the apotheosis dev to see if he can help us forward with it.

**Comment by Patrigan** [comment]
We have a preliminary datapack available on our discord. We will be expanding on this, now that our 4 piece armor sets are released.
Expect it to become core to the mod in the near future.
