### ISSUE TITLE
[1.16.5] Tumblebee Bees choosing violence in the Atum

### ISSUE THREAD

**Issue by Darkmega18** [Thelnfamous1/Dungeons-Gear#166]
Version: dungeons_gear-1.16.5-3.1.15-beta.jar
Forge: 1.16.5 36.2.39
Atum: Atum-1.16.5-2.2.11.jar

I had found some tumblebee enchanted boots at some point during an atum start in my modpack.
At one point, I dodged an enemy and it spawned a bee that helped me and survived the fight. Later I realized the bee was highly aggressive towards villagers of the atum when I reached the nearby village. Due to the no pet damage I was unable to stop the bee constantly going in to stab the villagers and so had to resolve it by picking up the bee with carry on and then dunking it in a nearby oasis...
On the way there it seemed to be angry towards some of the passive animals like quails potentially also.

All of the atum mobs etc had already been placed in the effect blacklist list at this time.

**Comment by Patrigan** [comment]
Could you share your config list? This could happen if an entry in the list is not recognized (typo?). I have just tested locally with default configs. They were aggressive to cats (didn't add those to the default list, they are now), but not to villagers.

**Comment by Darkmega18** [comment]
something like this:
`	effectTargetBlacklist = ["guardvillagers:guard", "minecraft:bat", "minecraft:bee", "minecraft:chicken", "minecraft:cod", "minecraft:cow", "minecraft:dolphin", "minecraft:donkey", "minecraft:fox", "minecraft:horse", "minecraft:iron_golem", "minecraft:mooshroom", "minecraft:ocelot", "minecraft:panda", "minecraft:parrot", "minecraft:pig", "minecraft:polar_bear", "minecraft:pufferfish", "minecraft:rabbit", "minecraft:salmon", "minecraft:sheep", "minecraft:squid", "minecraft:strider", "minecraft:trader_llama", "minecraft:tropical_fish", "minecraft:turtle", "minecraft:villager", "minecraft:wandering_trader", "minecraft:wolf", "ars_nouveau:ally_vex", "ars_nouveau:blazing_weald_walker", "ars_nouveau:carbuncle", "ars_nouveau:cascading_weald_walker", "ars_nouveau:drygmy", "ars_nouveau:dummy", "ars_nouveau:familiar_bookwyrm", "ars_nouveau:familiar_carbuncle", "ars_nouveau:familiar_drygmy", "ars_nouveau:familiar_jabberwog", "ars_nouveau:familiar_sylph", "ars_nouveau:familiar_wixie", "ars_nouveau:flourishing_weald_walker", "ars_nouveau:summon_horse", "ars_nouveau:summon_wolf", "ars_nouveau:sylph", "ars_nouveau:vexing_weald_walker", "ars_nouveau:whelp", "ars_nouveau:wixie", "atum:camel", "atum:desert_rabbit", "atum:desert_wolf", "atum:quail", "atum:quail_egg", "atum:serval", "atum:stoneguard_friendly", "atum:stonewarden_friendly", "atum:villager_female", "atum:villager_male", "betterendforge:dragonfly", "betterendforge:end_fish", "betterendforge:shadow_walker", "cavesandcliffs:axolotl", "cavesandcliffs:glow_squid", "cavesandcliffs:goat", "charm:coral_squid", "charm:moobloom", "doggytalents:dog", "endergetic:booflo", "endergetic:booflo_adolescent", "endergetic:booflo_baby", "endergetic:puff_bug", "endermail:ender_mailman", "environmental:deer", "environmental:duck", "environmental:duck_egg", "environmental:fennec_fox", "environmental:koi", "environmental:slabfish", "environmental:yak", "farmingforblockheads:merchant", "iceandfire:amphithere", "iceandfire:hippocampus", "iceandfire:hippogryph", "iceandfire:hippogryph_egg", "iceandfire:myrmex_egg", "iceandfire:myrmex_queen", "iceandfire:myrmex_royal", "iceandfire:myrmex_sentinel", "iceandfire:myrmex_soldier", "iceandfire:myrmex_swarmer", "iceandfire:myrmex_worker", "iceandfire:pixie", "iceandfire:siren", "inventorypets:bed_pet_entity", "inventorypets:bill_gates_entity", "inventorypets:mini_quantum_blaze_entity", "inventorypets:mini_quantum_enderman_entity", "inventorypets:satya_nadella_entity", "inventorypets:siamese_entity", "inventorypets:steve_ballmer_entity", "losttrinkets:dark_vex", "mowziesmobs:baby_foliaath", "mowziesmobs:barakoan_player", "mowziesmobs:foliaath", "mowziesmobs:grottol", "mowziesmobs:lantern", "mutantbeasts:creeper_minion", "mutantbeasts:creeper_minion_egg", "mutantbeasts:endersoul_clone", "mutantbeasts:mutant_snow_golem", "mutantbeasts:spider_pig", "mysticalworld:beetle", "mysticalworld:deer", "mysticalworld:endermini", "mysticalworld:frog", "mysticalworld:hell_sprout", "mysticalworld:lava_cat", "mysticalworld:owl", "mysticalworld:silkworm", "mysticalworld:silver_fox", "mysticalworld:sprout", "outer_end:chorus_squid", "outer_end:spectrafly", "outer_end:stalker", "quark:crab", "quark:foxhound", "quark:frog", "quark:shiba", "quark:stoneling", "quark:toretoise", "savageandravage:creepie", "tombstone:grave_guardian", "villagertools:guard", "villagertools:reinforced_golem"]`
it's kinda huge cause it's from my modpack. I might have to go in and test it around some of these other mobs to see if I indeed do have a typo in there somewhere.

**Comment by Patrigan** [comment]
Could you send me a latest.log? That often tells me if there's an issue with anything.

**Comment by Darkmega18** [comment]
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/9693932/latest.log)
sorry, github logged out so never noticed a reply until I checked emails. Um, thats the latest latest.log that I got.

**Comment by Patrigan** [comment]
Should be fixed in Dungeons Libraries 0.0.18-beta. 
Summoned mobs will no longer attack passive mobs (except if their master does)
