### ISSUE TITLE
What license is this mod?

### ISSUE THREAD

**Issue by Darkhax** [Thelnfamous1/Dungeons-Gear#167]
Similar to my question on https://github.com/Thelnfamous1/Dungeons-Mobs/issues/139, what license is this mod using? The `mods.toml` file and CurseForge page say MIT however the actual license file states LGPL 2.1.

**Comment by Thelnfamous1** [comment]
It's meant to be MIT, I was not aware I needed to supply a different license file as well.

**Comment by Darkhax** [comment]
You don't necessarily need to supply a difference license file, however the source code on GitHub is currently listed as LGPL 2.1 which you can see [here](https://github.com/Thelnfamous1/Dungeons-Gear/blob/alpha/LICENSE.txt)

**Comment by Patrigan** [comment]
Updated to MIT License.
