### ISSUE TITLE
Mixin config crash 1.16.4

### ISSUE THREAD

**Issue by 3x1at1on** [Thelnfamous1/Dungeons-Gear#17]
Game is crashing upon launch with mixin config create/read error.
Minecraft 1.16.4
Forge 35.0.15
Dungeon Gear 3.0.1

Log https://pastebin.com/Birs47RH

**Comment by Thelnfamous1** [comment]
No clue what is causing this. Can you run the mod on older versions, like 1.16.2/1.16.3?

**Comment by 3x1at1on** [comment]
Works perfectly on 1.16.3

**Comment by 3x1at1on** [comment]
Forge issue. Fixed in 35.0.18
