### ISSUE TITLE
Lucky Explorer can't be applied.

### ISSUE THREAD

**Issue by ZoeyPageOfSpace** [Thelnfamous1/Dungeons-Gear#170]
Version: dungeons_gear-1.16.5-3.1.15-beta.jar
Forge: 1.16.5 36.2.39

Currently running DG in a modpack and the enchantment "Lucky Explorer" can't be applied to anything except the set it comes on. If you get it on a book, it's unusable.

**Comment by Jackiecrazy** [comment]
did you remove it from the enchantment blacklist in the config? Lucky explorer is sealed away by default to prevent cries of imbalance.

**Comment by Patrigan** [comment]
Jackiecrazy already answereed this. You should also no longer be getting it on a book if all is well.
