### ISSUE TITLE
Most Dungeons Armor and Weapons misplaced and does not have enchantment effects (1.16.5-3.1.17-beta)

### ISSUE THREAD

**Issue by gummie2022** [Thelnfamous1/Dungeons-Gear#171]
When I look in the Fox Hood and Fox Vest enchantments, it's missing but got misplace them in Fox Leggings and Fox Boots instead. Also, this impacts other armor and weapons, yet some of them have missing stats and enchantments.

**Comment by Patrigan** [comment]
I'm going to need a bit more. What do you mean with misplaced?

**Comment by gummie2022** [comment]
for instance, fox hood supposedly have melee aura I, potion aura I, and dodge then it was misplaced to fox leggings and fox boots

**Comment by gummie2022** [comment]
also, other dungeon armors and weapons does not have enchantments at all like ocelot armor

**Comment by Patrigan** [comment]
hmmmm
can you try typing /reload in the chat?

**Comment by Patrigan** [comment]
AH WAIT! Yes

We have limited enchantments to only one piece going forward. Some enchants were not meant to be stacked and we got some complaints from people that really disliked how many enchants we allowed on one piece.

This caused us to reshuffle our enchants a bit on our pieces. Sorry for the inconvenience.

**Comment by gummie2022** [comment]
it's alright and tyt with it

**Comment by gummie2022** [comment]
Frost Bite and Ember Armor still have no enchantment effects or simply plain white text in 1.16.5-3.1.18-beta
![image](https://user-images.githubusercontent.com/108954683/202840597-fd735d4b-da39-4595-bf37-e4cc6e57ae32.png)
![image](https://user-images.githubusercontent.com/108954683/202840603-4af63fcd-f137-4432-b2da-6d65e08fc7e2.png)

**Comment by gummie2022** [comment]
hopefully fix the rest of it for 3.1.19

**Comment by Patrigan** [comment]
Fixed in latest release.
