### ISSUE TITLE
Unsure which mod is causing the issue (1.16.5)

### ISSUE THREAD

**Issue by SweetestBoy** [Thelnfamous1/Dungeons-Gear#173]
I really want to use Dungeons Gear, Valkyrien Skies, and Eureka! Airships. I have all the dependents that are required by each mod. I have ran each mod independently without issue. The issue arises when starting an instance of minecraft with Dungeons Gears and Valkyrien Skies, though Eureka! Airships is dependent on Valkyrien Skies, it causes the game to crash without creating a crash log. I have enabled the game output to see what is causes the wrench being thrown. I am curious as to if these mods will possibly be compatible in the future or if your mod relies on a mix-in that is being modified by the other mod.
Here is the game output that states the issues:

> [11:58:18] [main/WARN] [mixin/]: @Redirect conflict. Skipping dungeons_gear.mixins.json:GameRendererMixin->@Redirect::getModifiedDistance1(Lnet/minecraft/util/math/vector/Vector3d;Lnet/minecraft/util/math/vector/Vector3d;)D with priority 1000, already redirected by valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer->@Redirect::correctDistanceChecks(Lnet/minecraft/util/math/vector/Vector3d;Lnet/minecraft/util/math/vector/Vector3d;)D with priority 1000

> [11:58:18] [main/WARN] [mixin/]: @Redirect conflict. Skipping dungeons_gear.mixins.json:GameRendererMixin->@Redirect::getModifiedDistance2(Lnet/minecraft/util/math/vector/Vector3d;Lnet/minecraft/util/math/vector/Vector3d;)D with priority 1000, already redirected by valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer->@Redirect::correctDistanceChecks(Lnet/minecraft/util/math/vector/Vector3d;Lnet/minecraft/util/math/vector/Vector3d;)D with priority 1000

> [11:58:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector getModifiedDistance1(Lnet/minecraft/util/math/vector/Vector3d;Lnet/minecraft/util/math/vector/Vector3d;)D in dungeons_gear.mixins.json:GameRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap dungeons_gear.refmap.json

**Comment by Patrigan** [comment]
Based on what I see here, Valkyrian Skies and Dungeons gear are literally incompatible.

I will take a look to see if I can rework this piece of code.

**Comment by SweetestBoy** [comment]
Thank you, I've also posted this post to the other GitHub for the other mod. Here is the link so you can see what is going on other other side from the other mod user. Here is a link so these mods can (hopefully) one day be compatible, https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/232.
Thank you again!

**Comment by SweetestBoy** [comment]
Any updates for the resolution or eta on it?

**Comment by Thelnfamous1** [comment]
This is a result of some hackery we did to get Attack Reach working, since there was no Forge-provided Attack Reach attribute until 1.18. Anyone else attempting to perform similar hacks as us to get their versions of Attack Reach working will inevitably cause incompatibility, unless we start using a library called MixinExtras as a part of our projects. 

Development is currently focused on the unstable 1.19.2 version of Gear, but in the long term we will look into backporting fixes as well as addressing version-specific issues such as this one.

**Comment by SweetestBoy** [comment]
Any updates? I know its been a year, and that development on 1.16.5 may no longer in the thoughts your development team's mind. I would like to know so I can consider if I just need to update my minecraft version which I am going to say took me a while since I went from 1.7.10 to 1.16.5 when all mod support for 1.7.10 disappeared and 1.16.5 was the latest version of minecraft at the time. I just have a hard time adjusting to a newer version for an unreasonable mental thing I still can't figure out.

**Comment by Thelnfamous1** [comment]
We are currently focused on 1.20+, and do not expect to backport anything/fix older versions in the near future.

**Comment by Thelnfamous1** [comment]
1.16.5 is no longer supported.
