### ISSUE TITLE
Ticking entity with chest in minecart 1.16.5-3.2.1

### ISSUE THREAD

**Issue by Sageking10** [Thelnfamous1/Dungeons-Gear#175]
I was walking towards a desert temple and the game suddenly crashed when generating loot from this mod in a minecart chest.
[crash-2022-12-02_17.46.50-server.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/10144844/crash-2022-12-02_17.46.50-server.txt)
[https://crashy.net/2E901qVXwq2nUwENM1IG](url)

**Comment by OrpheusOmega** [comment]
I'm having this exact crash happening as well, tried different versions of the mod and still the same thing in multiple worlds. Seems any time a Chest in a Minecart is loaded in, it crashes.
[crash-2022-12-17_12.30.57-server-COPY.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/10254181/crash-2022-12-17_12.30.57-server-COPY.txt)

**Comment by Patrigan** [comment]
![image](https://user-images.githubusercontent.com/1729466/209876679-af46bd98-a06e-4930-9933-32110dcdc99b.png)
Works fine for me in the latest version.
So either you need to update, or this is a mod conflict. Considering I'm not exactly doing something wonky with adding the loot, I could wonder if maybe another mod is breaking it.

**Comment by Patrigan** [comment]
I want to point out this mod is active in RAD2 and thus far there were no reports from this bug in their channels.

So I can only conclude this is an incompatibility with another. I would like to ask if you can try removing some mods and then visiting a mineshaft to see if it crashes. Once you find the culprit, let me know then we can talk again.

**Comment by gabvichiato** [comment]
yeah, happening to me as well, found the solution yet?

**Comment by Patrigan** [comment]
I can't recreate the problem. The mod is active in a pretty  big modpack, RAD2, and is not causing an issue there. So there must be a specific mod causing a problem.

I can't fix what I can't recreate. I hope someone can pinpoint a specific mod combination.

**Comment by Patrigan** [comment]
Good news, people in the discord mentioned End Remastered as the potential culprit. I will investigate the issue and see if we can fix this :)

**Comment by Patrigan** [comment]
Fix will be released later today.
I also sent a message to the End Remastered Developer, as he's doing something which isn't really the standard approach to things.
My bad for forgetting mod developers often don't follow standard practices xD

**Comment by SpecialtyK** [comment]
Unfortunately the latest update now causes a crash on startup vs being able to play up until certain loot generates. Tried with and without End Remastered and even with only the latest Dungeon Gear/Mobs/Library, Curios, and Geckolib enabled and no other mods.
[1.16.5 Log.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/10334011/1.16.5.Log.txt)

**Comment by Patrigan** [comment]
Since the method that crashes no longer exists in 3.2.6, I'll close the ticket now.
