### ISSUE TITLE
Incompatibilities?

### ISSUE THREAD

**Issue by Jetpack-Cat** [Thelnfamous1/Dungeons-Gear#176]
The world just hangs, then when you save and exit it freezes but doesn't crash. I have to crash the mod from task manager which produces no crash report

![2022-12-11_12 44 04](https://user-images.githubusercontent.com/100042170/206929988-9ba0d632-7300-4f10-b02b-d231d698a670.png)
![2022-12-11_12 43 58](https://user-images.githubusercontent.com/100042170/206929989-ffadcc73-c8a8-4830-aee5-e839558097aa.png)

**Comment by Patrigan** [comment]
I'll be needing much more than just this.

Clearly, you have a lot of other stuff going on there. So we'll have to see what's what and try to pinpoint what is actually happening.

**Comment by Patrigan** [comment]
We have fixed a very common server hang in a recent version. Please try updating. If that doesn't fix it, reopen the ticket.
