### ISSUE TITLE
Boss Gear misconfiguration causing crashes (apotheosis compat)

### ISSUE THREAD

**Issue by Naturaspell** [Thelnfamous1/Dungeons-Gear#177]
Hello

The "chestplates" key has been replaced by "chestfull_metals" in this boss gear config:
https://github.com/Thelnfamous1/Dungeons-Gear/blob/1.16.5/src/main/resources/data/dungeons_gear/boss_gear/plate_power_bow_unique.json

Causing NullPointerExceptions when apotheosis tries to summon a boss with this gear.

Thank you.

**Comment by Patrigan** [comment]
Fixed in upcoming 3.2.3
