### ISSUE TITLE
Weapons auto switching

### ISSUE THREAD

**Issue by Undetermlned** [Thelnfamous1/Dungeons-Gear#180]
Hey weapons are auto switching into the shield slot when you try to left click with them a few times, and when you hit an enemy.

I'm running on the 1.16.5 version

**Comment by Patrigan** [comment]
This is a new feature for light weapons we added, to replace the broken dual wield system we had. Howeer, it shouldn't have switched with an empty hand or a shield.
This will be fixed with the 1.0.3 release of Dungeons Libraries today.
