### ISSUE TITLE
Unable to enchant with mod's enchanted books

### ISSUE THREAD

**Issue by tara-pogancev** [Thelnfamous1/Dungeons-Gear#182]
I have a lot of enchanted books as drops from the mobs with enchantments from the mod. However, I am unable to enchant my tools and weapons with any of them using an anvil. I don't have this issue with other enchantments, even from other mods. 

I am playing on RAD2 modpack, version 16.5 of Minecraft, 3.1.18 beta of the mod.

**Comment by Patrigan** [comment]
They have disabled dungeons gear enchants on non-dungeons gear.
If you do wish this to be possible, hop into dungeons_gear-common.toml and set the following to true: enableEnchantsOnNonDungeonsGear
