### ISSUE TITLE
1.16.5 This mod removes transparency from the hotbar

### ISSUE THREAD

**Issue by Jetpack-Cat** [Thelnfamous1/Dungeons-Gear#184]
dungeons_gear-1.16.5-3.2.3.jar

The bg behind the items in your hotbar is transparent until I add this mod
![image](https://user-images.githubusercontent.com/100042170/209928976-7010cbdb-9f1b-4cb1-8fe4-516656ac306a.png)

**Comment by Patrigan** [comment]
We don't touch the hotbar at all. However, I made some changes to our artifact bar, so it no longer uses the vanilla hotbar icons. Can you tell me which modpack you are using here?

It might be fixed with that. Please check if it still happens in Dungeons Libraries 1.0.4 (released soon)

**Comment by Patrigan** [comment]
Not fixed yet. I discovered the issue, will be releasing 1.0.5 later today :)

**Comment by Patrigan** [comment]
Fixed in Dungeons Libraries 1.0.5
https://www.curseforge.com/minecraft/mc-mods/dungeons-libraries/files/4287841
