### ISSUE TITLE
1.16.5 Add config to adjust position for these.

### ISSUE THREAD

**Issue by Jetpack-Cat** [Thelnfamous1/Dungeons-Gear#185]
Requesting you add a way to adjust the location of these 3 gui things so they don't overlap with other mods. 
![image](https://user-images.githubusercontent.com/100042170/209929219-bfea2232-2c6b-4065-bbb7-683fa1393f2e.png)

**Comment by Patrigan** [comment]
Config already exists for these in the form of a resourcepack:

{
  "sizeX": 48,
  "sizeY": 22,
  "offsetY": 0,
  "offsetX": -60,
  "alignment":  "bottom_right",
  "isHidden": false
}
![image](https://user-images.githubusercontent.com/1729466/210247454-7bb673a1-7eca-4bc7-88a0-0bfe219d4221.png)
