### ISSUE TITLE
1.16.5 If I disable artifacts, then the artifacts slot gui should be hidden

### ISSUE THREAD

**Issue by Jetpack-Cat** [Thelnfamous1/Dungeons-Gear#186]
dungeons_gear-1.16.5-3.2.3.jar
I've turned off artifacts in the config. If I don't want to use the artifacts in my pack, this gui should be hidden. I'm guessing that disabling the added interface gui would probably fix the other graphical issues going on as well, where the hotbar background is no longer transparent, and the ftbchunks mini map and world map are messed up.

I like this mod and want to use it in my next modpack but the gui issues are kind of big and ruin the aesthetic i'm going for.

![image](https://user-images.githubusercontent.com/100042170/209931036-9a938218-57ea-41f9-83c1-18a351074f67.png)

**Comment by Patrigan** [comment]
As mentioned in the other issue, you can now remove the bar using a resourcepack.

The enableArtifactLoot only disables the dropping of artifacts from the loottables. It doesn't actively disable artifacts completely.
