### ISSUE TITLE
apparently this mod is causing crashes. as i don't actually know whether it's it or an incompatibily between this one and others, i'm posting here for help

### ISSUE THREAD

**Issue by gabvichiato** [Thelnfamous1/Dungeons-Gear#189]
so what happens is whenever i grab a modded enchanted item the game crashes and gives me what's written in here: https://pastebin.com/KdrsL1zk

i don't believe it's caused by this mod, but on the crash report it refers this one quite a lot and on the first lines too, so i figured i should ask for help in here. could it be incompatibility? thank you in advance. by the way, the way it crashes is upon picking given modded enchanted item and also using it, so i can even show what kind of items make the crashes happen. other than that the game functions properly.

i believe it's related to apotheosis or ensorcellation, as these are the only mods related to enchantment i have (i guess))

**Comment by Patrigan** [comment]
I have gotten this report through discord and fixed it. Will be releasing the fix version soon.

**Comment by Patrigan** [comment]
Thisd should be fixed in the latest libraries version
