### ISSUE TITLE
Love charm can cause corruptions with other modded entities

### ISSUE THREAD

**Issue by Catlord-3** [Thelnfamous1/Dungeons-Gear#190]
Basically, when used on certain modded entities, the love charm can cause corruptions that make a world crash whenever you try to load it. One example is the OB Aquamarine captain boss which corrupts when used near it. The only way to fix it that i have found is to uninstall the mod, load the world, and reinstall the mod to clear whatever value is causing the issue. This makes using it on any unknown modded entity a risk as it could cause continuous crashes, and uninstalling and reinstalling wipes all items. Could you please look into this.

**Comment by Patrigan** [comment]
There is a field in the cofnig called loveMedallionBlacklist.
I advise adding the mobs you encounter that are bugged there.

There are so many modded mobs, but most of them actually work. So it seemed better to make a blacklist that modpackers can add to.

If you could share a crashlog, then I can look into why it crashed and maybe make it a bit more resilient, unless Aquamarine is doing something really funky...

**Comment by Thelnfamous1** [comment]
@Catlord-3 Can you provide a crash log resulting from a recreation of this issue you were having? Additionally, what version is this issue present on?

**Comment by Thelnfamous1** [comment]
Closing due to no further elaboration.
