### ISSUE TITLE
Dungeons Gear Crash on Start up [1.16.5-3.2.5]

### ISSUE THREAD

**Issue by aarter180** [Thelnfamous1/Dungeons-Gear#192]
The latest version of Dungeons Gear crashes on start up without producing a crashlog, not even when I look in the crash log folder in files, so here is the latest log after I removed every mod besides required dependencies (couldn't find any guidelines or formats for writing issues so sorry in advance):

[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/10334671/latest.log)

**Comment by Patrigan** [comment]
Please check Dungeons Gear 3.2.6, which has just been added to CF. Should fix the issue.
