### ISSUE TITLE
Artifact GUI still displayed with Dungeons Gear uninstalled

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Gear#194]
The GUI for artifacts is still displayed on screen with Dungeons Gear removed.  

As a side note, I have Dungeons Mobs and the library mod to go with it. If the library mod is rendering a GUI dedicated to the gear mod, perhaps it should have a dependency check?

**Comment by Patrigan** [comment]
Dungeons Mobs also contains several artifacts that can be used, these are a bit rarer, but hence why the bar is still there.

You can disable the bar using a texture pack.
