### ISSUE TITLE
armors need more durability

### ISSUE THREAD

**Issue by EaSy00MoNeY01** [Thelnfamous1/Dungeons-Gear#195]
less of an issue, more of a recommendation. >300 durability for every piece of armor is crap. it cant be used, this mod is basically pointless until the durability is increased to a point where its usuable. getting by armor broken in a couple hits by strong mobs after spending literally hours making your gear into god armor to fight said strong mobs, is one of the most frustrating things ive ever experienced in a game of modded minecraft.

**Comment by Patrigan** [comment]
I hear you, we're considering improvements. Due to the availability, we don't want it to be diamond level gear.

You can, however, already upgrade the durability using a datapack, where you change the available armor materials of Dungeons Gear. This allows you to increase the durability.
