### ISSUE TITLE
[1.16.5-3.2.6] Vanilla Critical Hit Damage Boost doesn't work with melee weapons of the mod

### ISSUE THREAD

**Issue by AlanightCreeper** [Thelnfamous1/Dungeons-Gear#196]
When I jump and then attack the Target Dummy with every melee weapon of Dungeons Gear, I find that the damage doesn't be changed. Here is the video:

https://user-images.githubusercontent.com/82942121/211739508-a57cbb07-cd34-45dd-8630-2f4eb5fa5e1e.mp4

**Comment by Patrigan** [comment]
Interesting. I think we dropped that in favour of the combo system, where the last hit in the combo is effectively the equivalent of a critical hit.

I'm wondering if we should make this configurable and also more visible.

**Comment by AlanightCreeper** [comment]
No wonder the critical hit particles sometimes appear suddenly when strike a combo. But I find that the damage of last hit in the combo isn't changed🤔.
Configurability is great to me, and also visualization. I love highly configurable mod. But I don't know the opinions of you and other players. If you think it's necessary, implement it.

**Comment by Thelnfamous1** [comment]
1.16.5 is no longer supported.
