### ISSUE TITLE
[1.18.2] Swords copies of Minecraft weapons

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Gear#200]
I understand the goal is to replicate most/all the content in Minecraft Dungeons, but Minecraft already has (stone/gold/diamond) swords. Perhaps the swords should be removed in favour of existing vanilla content?

**Comment by Patrigan** [comment]
The current issue is that we can't add Dungeons effects to these vanilla items. We're trying to figure out a solution.

One suggested solution is to replace the vanilla tools with our Dungeons tools. Thatb seems like an option, but might not be the greatest.

For now, we opted to have both exist.

**Comment by MarioSMB** [comment]
I see, hopefully there's a way to make the effects modular enough to support non-Dungeons Gear items.
