### ISSUE TITLE
Copies of other mods in repository

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Gear#202]
The [mods](https://github.com/Infamous-Misadventures/Dungeons-Gear/tree/alpha/mods) folder in the source code repository contains binaries for OptiFine and Dungeons Libraries.  
Just thought I'd mention it since OptiFine has a bit of a policy against rehosting!

**Comment by Patrigan** [comment]
Oh, fair point, that was a leftover from a test, because their mod broke a bunch of shit. I hate optifine sometimes xD

Will delete it!

Dungeons Libraries is our own mod, so there's no issue there.

**Comment by MarioSMB** [comment]
Hah, here's hoping Rubidium becomes the defacto performance mod, thanks!
