### ISSUE TITLE
[1.16.5] [3.2.6] Friendly Fire giving error

### ISSUE THREAD

**Issue by NekoTZN** [Thelnfamous1/Dungeons-Gear#204]
When i tried to enable friendly fire on pets it gives me an error when i open minecraft, and i can't access some content from Mahou Tsukai mod cause i need to kill a tamed dog. The "Configured" mod helped me to change it, but changing the config from file gives an error.

And why the f* the crash report just said "you're mean".

Edit: saw i just changed it wrong xD was writing "enable" instead of true

**Comment by Patrigan** [comment]
The best issues are the ones where I have to do no effort.
