### ISSUE TITLE
Final Shout crash on player death

### ISSUE THREAD

**Issue by DaedalusGame** [Thelnfamous1/Dungeons-Gear#21]
Crash log: https://gist.github.com/DaedalusGame/5c6c6c93981b7907f014591a6b6fc2cd

Seems to happen anytime a player with the Final Shout enchant dies, but said player has very very low health, so I'm not convinced it just happens when one dies.

**Comment by Thelnfamous1** [comment]
Ah, simple sidedness issue. Easy fix, expect it out in a bit.

**Comment by Thelnfamous1** [comment]
It's up.
