### ISSUE TITLE
Auto crossbow not working as intended 

### ISSUE THREAD

**Issue by Merc664** [Thelnfamous1/Dungeons-Gear#210]
The auto crossbow would just work like a regular crossbow would

**Comment by Thelnfamous1** [comment]
To be clear: Our auto crossbow is not automatic in the way that a gun is. How it works is that the charging speed gets faster and faster the more you shoot in a given amount of time, ending up nearly automatic by the end. You will always need a click to charge it and a click to fire it, the only difference is how long you need to hold down the first click.

Given this explanation, does this match what you are seeing in game?

**Comment by Thelnfamous1** [comment]
May be related: https://github.com/Infamous-Misadventures/Dungeons-Gear/issues/215

**Comment by Thelnfamous1** [comment]
Closing, because #215 was fixed and I can see no other reason why the auto crossbow would not be working without more details.
