### ISSUE TITLE
[1.18, 1.19.2] Spammable weapons

### ISSUE THREAD

**Issue by LittleManDiscord** [Thelnfamous1/Dungeons-Gear#214]
Looks like in 1.19.2 as well as 1.18 version has a bug where the weapons have no cooldown. Not sure if this is affected by speed but it seems like every weapon is affected by this bug from experience.

https://user-images.githubusercontent.com/124035152/215708709-5be77f60-3ebc-4d00-ae0f-8385cb5d82f1.mp4

**Comment by Thelnfamous1** [comment]
This is an issue with Dungeons Libraries. We've pinpointed the issue and it will be fixed in the next release of it.

**Comment by Thelnfamous1** [comment]
Fixed for 1.19.2 by next release. https://github.com/Infamous-Misadventures/Dungeons-Libraries/issues/31

**Comment by Thelnfamous1** [comment]
Closing as completed for 1.19.2. 1.18 is no longer supported.
