### ISSUE TITLE
[1.19.2] Critically crashes with Optifine.

### ISSUE THREAD

**Issue by karovania** [Thelnfamous1/Dungeons-Gear#220]
Tried to see if this incompatibility was listed anywhere, but I've yet to find text stating it.

**Comment by sodacanned** [comment]
i have this problem as well! dont understand why this would happen

**Comment by Patrigan** [comment]
My best advice right now, until we fix it:
Stop using Optifine. Use a combination of Rubidium, Occulus and CTM to get pretty much the same result, but just better , cleanerand more mod friendly.

OptiNotFine is really one of the worst mods in the modding community...

**Comment by Thelnfamous1** [comment]
Optifine compatibility will not be sought out.
