### ISSUE TITLE
equipping crashes the client

### ISSUE THREAD

**Issue by Ab14ew** [Thelnfamous1/Dungeons-Gear#221]
so I wore renegade helmet while my friend is behind me, He crashed and showed this 
![image](https://user-images.githubusercontent.com/42169348/219329973-f52dbf8f-60d2-46f8-99cf-324811d62e51.png)
he reconnected and I gave it to him, he equipped it and boom it crashed again with the same error

Minecraft 1.19.2
forge: 43.2.4
we played on a server not lan

**Comment by Thelnfamous1** [comment]
Duplicate or related to https://github.com/Infamous-Misadventures/Dungeons-Libraries/issues/32

**Comment by Thelnfamous1** [comment]
Fixed in latest version of Dungeons Libraries (1.19.2-3.0.9-beta).
