### ISSUE TITLE
[1.18.2] CTD when equping armor 

### ISSUE THREAD

**Issue by shiinano** [Thelnfamous1/Dungeons-Gear#222]
Heres my crashlog, sorry im not good with this stuff but the game freezes and crashes when equiping armor

https://paste.atlauncher.com/view/962ca4a9-793a-4239-8864-121fd489f5a9

**Comment by Thelnfamous1** [comment]
Try playing around with the version of 1.18.2 GeckoLib you are using, either using a later 1.18.2 version or an older one. The crash is caused by Dungeons Gear using Geckolib code that may have been removed in a later version or did not exist yet in an older version.

**Comment by Thelnfamous1** [comment]
@shiinano Any updates? Is this still a problem?

**Comment by Thelnfamous1** [comment]
Closing due to no further elaboration.
