### ISSUE TITLE
[1.19.2] Armor doesn't scale with baby zombies

### ISSUE THREAD

**Issue by WenXin20** [Thelnfamous1/Dungeons-Gear#224]
Dungeons Gear v5.0.4-beta
Dungeons Libraries v3.0.9-beta
Minecraft v1.19.2

Armor doesn't scale with baby mobs properly

![image](https://user-images.githubusercontent.com/12000593/220529601-3235f25e-4a85-4724-8967-4d27af2619b2.png)

**Comment by Patrigan** [comment]
Reported it forward to Gekcolib3
https://github.com/bernie-g/geckolib/issues/419
