### ISSUE TITLE
[1.19.2] Crash while running Minecraft using Optifine

### ISSUE THREAD

**Issue by FirdausCraft10** [Thelnfamous1/Dungeons-Gear#227]
This mod is one of my favorite mod, but please fix this unexpected crash

**Comment by Patrigan** [comment]
Duplicate of #220

**Comment by Patrigan** [comment]
Also, stop using Optifine. Use a combination of Rubidium, Occulus and CTM to get pretty much the same result, but just better , cleanerand more mod friendly.
