### ISSUE TITLE
[1.19.2] Server crash fix for a specific build?

### ISSUE THREAD

**Issue by xenornithos** [Thelnfamous1/Dungeons-Gear#228]
I've noticed an issue that's been mentioned before and fixed in the latest builds, but am wondering if it's possible to have this fix for a _specific earlier_ build (since newer builds immediately crashing the game for me) -- it's the issue on multiplayer servers where every time a player equips any Dungeons Gear armour piece, the other player is kicked out of the server due to a "SoundEvent" error. There is **Sound Physics Remastered** in my modpack, if that matters.
And, again, while fixed for newer builds, those crash the game because of (by assuming what might be) **OptiFine HU_I1**, which I need for certain things to work in my modpack.

That said, **Dungeons Gear 1.19.2-5.0.2-beta**, **Dungeons Libraries 1.19.2-3.0.6-beta**, and **Dungeons Mobs 1.19.2-4.0.3-beta** are the working set, despite only the gear-equipping, player-kick situation. I inquire if it's possible to implement the fix in those builds, since they're the only ones I can use.
Alternatively, if the instant crash at startup is possible/preferred/easier to resolve, hopefully that could be an option.

It's understandable if this may not be doable, but I wanted to at least try asking.

**Comment by Thelnfamous1** [comment]
We don't backport fixes to specific earlier builds of the same Minecraft version. As these are beta builds, you should be using them under the understanding that they are inherently unstable and the most recent version is always the least unstable. We are also not interested in establishing compat with Optifine, as it being a closed-source mod means we cannot determine where incompatibilities are happening.

**Comment by xenornithos** [comment]
Ah, okay. Thanks for the response and explanation.
