### ISSUE TITLE
[1.19.2] Weird floating armor far away from player

### ISSUE THREAD

**Issue by LittleManDiscord** [Thelnfamous1/Dungeons-Gear#230]
![2023-03-09_20 10 59](https://user-images.githubusercontent.com/124035152/224221649-a24d1496-5687-438c-8e29-afda23643c55.png)
![2023-03-09_20 11 03](https://user-images.githubusercontent.com/124035152/224221668-679934f4-0bb1-401b-8d8a-cc2fc00fc577.png)
![2023-03-09_20 11 09](https://user-images.githubusercontent.com/124035152/224221679-c49407c7-a292-4b9d-871a-33f9b1139499.png)

found a weird bug where armor would both be on my character and far away at the same time. Not sure if caused by another mod but can be seen on legendary tooltips

**Comment by Thelnfamous1** [comment]
Geckolib bug, not ours to fix.
