### ISSUE TITLE
[1.19.2] kind of enchantment overlaps max health

### ISSUE THREAD

**Issue by B-Wither** [Thelnfamous1/Dungeons-Gear#233]
I increased health about 15 hearts by using function in "Paraglider" mod, but when I equipped armor with enchantments "Cowardice III, Beast Boss I, Arrow Hoarder II, Reckless II", increased health became only two hearts.

**Comment by Patrigan** [comment]
Reckless reduces your health by 40%. I can not comment how the paraglider mod makes the change. Taking of the reckless should return it to normal.

An update will release to the enchant in 5.0.5-beta which will reduce the impact of this health reduction.
