### ISSUE TITLE
Failure message: Mod dungeons_gear requires dungeons_libraries 1.19.2-3.0.10-beta or above

### ISSUE THREAD

**Issue by ModernGamingWorld** [Thelnfamous1/Dungeons-Gear#238]
Mod File: /C:/Users/Home2/curseforge/minecraft/Instances/Monumental Experience (1)/mods/dungeons_gear-1.19.2-5.0.5-beta.jar
	Failure message: Mod dungeons_gear requires dungeons_libraries 1.19.2-3.0.10-beta or above

**Comment by Thelnfamous1** [comment]
The next libraries version has now been submitted for approval on Curseforge. Sorry about the delay!
