### ISSUE TITLE
The mod never works

### ISSUE THREAD

**Issue by ShieldManH** [Thelnfamous1/Dungeons-Gear#24]
I saw this mod in vault hunters on twitch with iskall85 and his pals. However, the accompanying mods such as pillagers with armor, armed villagers, etc... are working fine. Whenever I put the Dungeons gear mod, the game does not even load. This is a picture of what happens. I tried removing the mod, and the game works fine. Put the mod, the game never starts. I tried to apply it alone and it did not work, on two mega modpacks and also did not work. Please help.
Thank you.
Sincerely, ShieldManH.

![Screenshot (151)](https://user-images.githubusercontent.com/76407731/102723303-e62dc480-4317-11eb-851b-c657e1dd0c38.png)

**Comment by Thelnfamous1** [comment]
I need to see a crash log and a latest.log. Please always include those in your mod issue reports.

**Comment by ShieldManH** [comment]
Sorry, I didn't include them. This is the first time I report something because I wanted it to work so badly.
Note: About the crash report, when the problem of Exit Code: 0 happens as in the photo included, there is no crash report. So I added mods without their library mods intentionally so it gives a crash report. Hope this will do the work.

[crash-2020-12-21_23.45.28-fml.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/5726482/crash-2020-12-21_23.45.28-fml.txt)

[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5726457/latest.log)

Thank you for your time. 
Sincerely, ShieldManH.

**Comment by Thelnfamous1** [comment]
Ah, let me guess: You are playing with Resourceful Bees!

**Comment by ShieldManH** [comment]
Yes, Resourceful Bees is a stable mod as far as I remember because I use it everywhere. Dungeons gear, however, first time trying it. Don't they go hand in hand? I am confused but you know better than me because what does a resources mod have anything to do with items that generate in treasures or loot?
Thank you again for your time.

**Comment by Thelnfamous1** [comment]
They change the access level of an AI function for bees from protected to public. I have code that expects the access level to be protected, and will crash if it has been changed to public. This function’s access level does not need to be changed at all, so it is entirely their fault and I have told them about this but they have not fixed it.

**Comment by Thelnfamous1** [comment]
This should be fixed in latest version, try it out.
