### ISSUE TITLE
[1.19.2] Reckless is activating and reducing health while in the hand on a chestplate.

### ISSUE THREAD

**Issue by Darkmega18** [Thelnfamous1/Dungeons-Gear#241]
So in 1.19.2 a random apotheosis boss came and suicided some gear into my possession. it was a chestplate with reckless 3 and it seems be instantly reducing my health and activating it's effect as soon as it enters my hand, and not even being put on.

But further more, potentially due to some other bugs the heal reduction is remaining even when throwing the item out. putting it on and taking it off to try to nullify the effect. and only dieing resets it. but the moment it goes back into my hand it's stuck again and I gotta kill myself again.

I have a couple mods that do additional health if they might be testing points if the bug is actually not a thing at base, such as attributes from apotheosis affixed gear, Scaling health _(of which I had no hearts active cause I had them set as non-useable in config in hopes of using something else)_, and paraglider _(the something else. which I also don't have any heart containers in currently.)_

But tl:dr, reckless is activating in hand. Locks my health to 60% reduced until suicide. Uncertain if I'm keeping the damage buff along with it.

**Comment by Totomio** [comment]
Hi, i have a similar issue, i test it with with dungeon gear/libraries mods alone and the bug remain. You can just relaunch your map instead to comit suicide to reset your life points. For now until a fix, you can also disable this enchantment in the dungeons_gear-common config file by adding this "dungeons_gear:reckless" in the enchantmentBlacklist line.

**Comment by Thelnfamous1** [comment]
Should have been fixed by @Jackiecrazy's linked commit

**Comment by Darkmega18** [comment]
noice. does this mean 1.20 soon? :o
