### ISSUE TITLE
Farmers delight crash

### ISSUE THREAD

**Issue by UrBoiTom** [Thelnfamous1/Dungeons-Gear#242]
More info [here](https://github.com/vectorwing/FarmersDelight/issues/714)

**Comment by ModernGamingWorld** [comment]
@Thelnfamous1 any update on this, as this is causing an issue in my modpacks and I need it fixed so people can have the server stop crashing

**Comment by Thelnfamous1** [comment]
Should have been fixed by @Jackiecrazy's linked commit
