### ISSUE TITLE
Eureka Airships compatibility

### ISSUE THREAD

**Issue by FebKB** [Thelnfamous1/Dungeons-Gear#243]
Hello,
I made a modpack called Chivalry and Wizardry, a modpack which mixes Dungeon adventuring and Base building with magic mods + Create. I really wanted to install the Eureka Airships mod but it's incompatible with this mod too. I don't know exactly what is the incompatibility they have, but if it would possible, I want to ask you to make them compatible (for the 1.16.5 version, that is)

**Comment by FebKB** [comment]
Wait, I actually saw there is another post about it, my bad. I just really would love to have those mods working in conjunction.

**Comment by Thelnfamous1** [comment]
1.16.5 is no longer supported. If you happen to make a new modpack for 1.19.2 and the issue still persists, please remake it as a new issue.
