### ISSUE TITLE
(1.19.2) Rendering bug

### ISSUE THREAD

**Issue by DragesNolya** [Thelnfamous1/Dungeons-Gear#249]
When wearing armorsets from minecraft dungeons mod and using shaders(Rethinking Voxels and Complimentary reimagined), the armor appears near the crosshair in the distance.
This rendering issue does not occur with vanilla armor nor elytra.
screens shots on my modded server, 1.19.2, with complimentary reimagined, running using the oculus mod, which is a fork of Iris

![2023-07-06_21 06 06](https://github.com/Infamous-Misadventures/Dungeons-Gear/assets/26582369/21bca4e4-8c7f-495f-9592-8ff15e68861c)
![2023-07-06_21 06 08](https://github.com/Infamous-Misadventures/Dungeons-Gear/assets/26582369/27f0ba97-e992-4661-855e-a9b40cdd2d99)
![2023-07-06_21 06 16](https://github.com/Infamous-Misadventures/Dungeons-Gear/assets/26582369/245bbce2-5623-4410-9417-c8702c7c6501)

**Comment by kaairu** [comment]
this is unfortunately an issue caused by geckolib which is what the armors use, so kinda unfixable unless geckolib fixes it
