### ISSUE TITLE
Could not find some text for translation

### ISSUE THREAD

**Issue by ooo0ip** [Thelnfamous1/Dungeons-Gear#25]
While editing a sentence to translate this mod into Korean, we found missing text data in the lang file.

As a result, only the name of the weapon and the enchantment title could be translated.

Here's the file I worked on.

https://drive.google.com/file/d/1QWhzXmU3XHl_qxMaLdIZM_g7I7sfgRV0/view?usp=sharing

**Comment by Thelnfamous1** [comment]
Ah so none of the items have description keys in the lang files. I am aware of that, it was a cumbersome task for me so I did not make any. I will try to add some in the near future.

**Comment by Thelnfamous1** [comment]
Added complete localizations in development, will be fixed in next release
