### ISSUE TITLE
Just a personal request

### ISSUE THREAD

**Issue by D-Bigboy-302** [Thelnfamous1/Dungeons-Gear#26]
Hi! Would there be any possibility of adding a config option to disable/enable certain features? Like having an option to disable all armors or all weapons, enchants etc. For me, I only want the armor and artifacts. I find the weapons and enchants a bit overwhelming.

Just a personal thing for me, figured I'd at least ask. Thank you for this amazing mod!

**Comment by Thelnfamous1** [comment]
My suggestion: Disable the mod’s loot handler. Disable the villager trades. Make your own datapack.

**Comment by D-Bigboy-302** [comment]
Alright, I don't really know anything about creating a datapack but there is good ole youtube lol I'll figure it out. Thanks for taking the time to respond!
