### ISSUE TITLE
Interacting with basket from Farmers delight causes crashes

### ISSUE THREAD

**Issue by Milinko1** [Thelnfamous1/Dungeons-Gear#261]
Link to issue posted on farmers delight https://github.com/vectorwing/FarmersDelight/issues/790
This mod has a problem with the basket from farmers delight and if you load a chunk with a preloaded basket it causes a crash

**Comment by Thelnfamous1** [comment]
Should have been fixed by @Jackiecrazy's linked commit

**Comment by Milinko1** [comment]
How?

**Comment by Milinko1** [comment]
> Should have been fixed by @Jackiecrazy's linked commit

How
