### ISSUE TITLE
1.16.5 game crash

### ISSUE THREAD

**Issue by rgt002** [Thelnfamous1/Dungeons-Gear#270]
Not sure if there is an incompatibility with another mod, or if the mod itself is broken. Crashes when spawning into the world, works fine when Dungeons gear mod is removed.

Dungeons gear version 1.16.5-1.8.2 and dungeons libraries mod version 1.16.5-1.0.6
Tested with Forge loader v36.2.39 and v36.2.41

Console crash log
https://paste.atlauncher.com/view/f7437ddf-716e-4e55-8cff-8da54342546d

**Comment by Thelnfamous1** [comment]
1.16.5 is no longer supported.
