### ISSUE TITLE
Is this mod just dead..?

### ISSUE THREAD

**Issue by Gamershy** [Thelnfamous1/Dungeons-Gear#271]
A lot of issues have been reported with little to no response, plug there's been a vast lack of updates despite many of these issues being quite problematic.
It's fine if the project is abandoned, but please give some form of confirmation if it is?

**Comment by AzaelKurosaki** [comment]
its not abandoned

**Comment by Thelnfamous1** [comment]
This mod is undergoing a large-scale rewrite for modern versions (1.20+) and will be repackaged into an all-in-one MCD content mod with Dungeons Mobs. I am also currently the only maintainer for this version, and I haven't had time to address any of the issues plaguing the 1.19.2 version of this mod and the ones related to it (Libraries, Mobs).
