### ISSUE TITLE
Sensory issues with Spelunker Gear

### ISSUE THREAD

**Issue by BronsonCarder** [Thelnfamous1/Dungeons-Gear#273]
Hello,

I'm autistic and the bat that the Spelunker Gear summons causes sensory overload for me, both with it's constant shrieking, and with the way it keeps darting at my face. 

I spent about an hour arguing with people on the RAD2 discord about this, before they finally said they couldn't do anything and sent me to you. 

Literally all I'm asking for is an option to toggle this bat off. Can even be a config option, I'm not picky.

**Comment by Thelnfamous1** [comment]
What led you to believe this is closed?

**Comment by BronsonCarder** [comment]
I closed it, because I don't actually expect anyone to care. The people on
the RAD2 Discord made it clear that they considered this a non-issue. Which
I find disappointing, but I'm just simply going to move on. There are a
shit-ton of mods and modpacks out there, I'll just find one that fits me
better.
