### ISSUE TITLE
Request: Add black list for AOE Enchants for vanilla/modded mobs

### ISSUE THREAD

**Issue by draklorx** [Thelnfamous1/Dungeons-Gear#30]
Can you add a blacklist configuration to set it so that certain mobs could not be affected by AOE enchants?

This will prevent me from killing off all the chickens in my farm every time I stand near them, or hurting the goblin traders who just want to give me a good deal on an OP enchant.

**Comment by Thelnfamous1** [comment]
Sure

**Comment by draklorx** [comment]
So I mentioned burning by name, but it might need to apply to other types of enchants than just pulse enchants. Example, my daughter reported that it's happening on the Thundering enchant as well. She attacked a hostile mob near a wolf which damaged the wolf as well and cause it to start attacking her.

**Comment by Thelnfamous1** [comment]
Sorry, I have been away from developing for a while, I have had a contributer working on the mod recently and they have added a mob blacklist for AoE abilities. It should be there in the latest version of the mod

**Comment by Jackiecrazy** [comment]
It exists now, so I'm closing this.

**Comment by kierheyl** [comment]
Thanks so much! Really cool to see this in the mod!
