### ISSUE TITLE
Request: Respect /team allies with effects

### ISSUE THREAD

**Issue by Not-February** [Thelnfamous1/Dungeons-Gear#32]
Minecraft has a built-in teams feature with an optional friendly fire toggle.

I'd like to request that when this is turned off(i.e. you cannot harm your teammates), negative effects from gear and enchantments do not affect your allies, but still affect players on other teams, as an alternative to having to turn off items affecting other players altogether.

**Comment by Thelnfamous1** [comment]
Yeah I’ll see what I can do

**Comment by Thelnfamous1** [comment]
Is this still an issue in the later versions that have been released?

**Comment by Febilian** [comment]
I haven't yet had the opportunity to test an update of the mod in a multiplayer setting and am unsure if I will be able to anytime soon or not, but I'll see if I can figure out a way to test it with a friend in the near future.

**Comment by Febilian** [comment]
Just tested with a friend. We were both on the same team, with friendly fire turned off(so we wouldn't damage each other), and using any artifact which does negative effects to nearby enemies still affect my teammate.

I apologize for not remembering the names of the items, but: the teammate was not launched by the book that launches nearby enemies into the air. And the beacon laser artifact doesn't damage a teammate, so that seems to be working properly. It's the application of negative potion effects that appears to be the problem.

**Comment by Febilian** [comment]
I guess something messed up my original reply, so to summarize:

I tested with a friend, using several artifacts in their vicinity and at them when we were both on a team with friendly fire disabled.

Artifacts which cause damage did not damage them(as expected). Artifacts which purely did something to nearby enemies like launching them in the air didn't affect them(as expected). But _anything_ that applies potion effects, positive or negative, still applies to teammates.

This is especially troublesome in the case of armor enchants that emit auras like slowing enemies and such.

So it seems like the main issue at this point is there being no differentiation between positive and negative potion effects where team-based allies are involved.

**Comment by Thelnfamous1** [comment]
@Jackiecrazy you wanna take a look at this?

**Comment by Patrigan** [comment]
I rewrote the targetting a bit in the upcoming beta version. @Febilian , if you are still around, keep an eye on the next beta release. If it's still an issue in that version, please reply here.
Else I'll close thise a short while after releasing the version.

**Comment by Patrigan** [comment]
Closing because team targetting should now be included.
