### ISSUE TITLE
Sounds for some enchantments global; no option to turn off spam.

### ISSUE THREAD

**Issue by mactso** [Thelnfamous1/Dungeons-Gear#34]
The Thunder enchantment sound effect is global.  As we get more players with Thunder, the constant thunder spam is getting to be a problem.
The Fuse Shot enchantment effect is global.   One player just started using it today and everyone can hear it.

Forge 34.1.42  Minecraft 1.16.3

**Comment by Thelnfamous1** [comment]
Yeah I know sounds are broken, I haven’t gotten around to fixing it yet.

**Comment by Thelnfamous1** [comment]
Sounds are getting fixed in the next update, turns out what I understood to be the volume of a sound actually gets multiplied by 16 and therefore if you have 1000 as the volume, it can be heard from 1000 chunks away...

**Comment by Thelnfamous1** [comment]
Fixed sounds being too loud in development, will be fixed in next release
