### ISSUE TITLE
Snowball enchant is causing server console spam leading to server crash

### ISSUE THREAD

**Issue by celsiusqc** [Thelnfamous1/Dungeons-Gear#37]
![image](https://user-images.githubusercontent.com/63996164/104554827-c9c93300-560a-11eb-9073-471421188073.png)
https://pastebin.com/8vgLMsGG

**Comment by Thelnfamous1** [comment]
If this is a prevalent issues then Snowball needs to be reworked heavily, because the current implementation of the enchantment is exactly how it works in Minecraft Dungeons

**Comment by Jackiecrazy** [comment]
Looking at the crash, the snowballs were teleporting through a ratlantis portal?

**Comment by Thelnfamous1** [comment]
Tentatively fixed according to Jackie.
