### ISSUE TITLE
REQUEST: Armor should have better protection stats

### ISSUE THREAD

**Issue by adamhaze8** [Thelnfamous1/Dungeons-Gear#38]
The textures and concepts of the diverse items are awesome, but the protection stats of the armor don't really make sense. If it's all just as good as iron armor then they become kind of obsolete with alternatives like diamond and netherite. Especially for stuff like the plated armor which is a sick concept but it's literally just iron armor that makes you slow. The little abilities barely do anything. Maybe you could make the stats tweakable in the config?

**Comment by Thelnfamous1** [comment]
Armors were buffed protection-wise in the most recent update
