### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tyrius1** [Thelnfamous1/Dungeons-Gear#4]
[crash-2020-10-30_17.55.15-server.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/5467845/crash-2020-10-30_17.55.15-server.txt)

I was exploring in creative.

Minecraft Version: 1.16.3
forge-34.1.25 
dungeons_gear-1.16.2+1.16.3-2.0.9

**Comment by Thelnfamous1** [comment]
Working on a fix now

**Comment by Thelnfamous1** [comment]
It's fixed in the latest release
