### ISSUE TITLE
Config to turn off categories

### ISSUE THREAD

**Issue by iamSleepl3ss** [Thelnfamous1/Dungeons-Gear#40]
A config option to turn off item categories?

Like turn off weapons and bows, and only add armors.
Or turn off armors, but add all weapons and bows.

**Comment by Thelnfamous1** [comment]
Will consider, I assume you mean in terms of loot generation and trades

**Comment by iamSleepl3ss** [comment]
Yes exactly! Thank you!

**Comment by Thelnfamous1** [comment]
Added in latest release
