### ISSUE TITLE
[1.16.5] Snowball enchantment attacks all creatures

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Gear#42]
The snowball enchantment shoots any mob close to the player, even passive and neutral mobs. This can aggro zombie pigmen.

Preferably the enchantment would only target nearby enemy mobs attacking the player.

**Comment by MarioSMB** [comment]
I'd also like to note that it attacks non-creature entities too (armor stands).

**Comment by Jackiecrazy** [comment]
There is now a configurable list of entities blacklisted from hostile targeting, so closing this.
