### ISSUE TITLE
Dungeons Gear not allowing Diamond to be used in Ender Storage

### ISSUE THREAD

**Issue by iMahco** [Thelnfamous1/Dungeons-Gear#46]
**Game**: 1.16.4
**Forge**:  35.1.36 and 35.1.37
**Mod Effected**: Ender Storage 1.8.+
**Expected Behavior**: Diamond at hand, right clicking the Latch makes the chest personal.

After adding Dungeons Gear the act of making it personal no longer works. You're able to aim at the latch just fine but attempting to right click it with a diamond opens the chest instead. 

Edit: As an added piece of information, Ender Storage allows you to use any item of your choosing to personalize a chest, but no matter the change in its config the problem persists once Dungeons Gear is added.

**Comment by Thelnfamous1** [comment]
@Jackiecrazy could this be because of the dual wield handler?

**Comment by Jackiecrazy** [comment]
my guess is yes. Since it's a pretty big issue, I'll push this fix first, and figure out the attack stuff later.

**Comment by Jackiecrazy** [comment]
This should be fixed once the next release is up. Craft all your diamonds into blocks then back, then they should work.
