### ISSUE TITLE
Incompability with Eidolon Rituals

### ISSUE THREAD

**Issue by froehlichA** [Thelnfamous1/Dungeons-Gear#47]
Modlist:
- [Eidolon](https://www.curseforge.com/minecraft/mc-mods/eidolon)
- [Dungeons Gear](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear)

**The bug:**
Eidolon's *Ritual of Purifying*, the *Sword of Sapping* Ritual and the *Sanguine Amulet* Ritual cease to function properly, consuming their ingredients but not producing their desired effects.

All three recipes use a potion as an ingredient, so the issue may be related to your mod changing something about them?

**To reproduce:**
- Place down a *Brazier*, a *Necrotic Focus* and 6 *Stone Hand*s according to the guide in Eidolon's *Ars Ecclesia* (in the Category *Rituals*).
- Place the ingredients in the *Stone Hand*s and the *Necrotic Focus* according to the pages *Ritual of Purifying* or *Sanguine Items*.
- The ritual starts and the ingredients get consumed, but the ritual completes unsuccessfully (No effect occurs / No output item gets produced).

**Related Issues:**
- https://github.com/elucent/eidolon/issues/55
- https://github.com/elucent/eidolon/issues/48

**Comment by Jackiecrazy** [comment]
This should be fixed by 0b3f1ad.
