### ISSUE TITLE
Default config is in some sort of debug mode?

### ISSUE THREAD

**Issue by kubistonek** [Thelnfamous1/Dungeons-Gear#50]
items spawn in chests too often, Im pretty sure its a bug, since in default config it says it should be X number by default, but the actual number shown is way bigger. Example: chance to spawn items in chest "[0.0-1.0, default: 0.15] #Range: 0.0 ~ 1.0 uniqueItemCommonLoot = 0.25

I think you were testing the mod and forgot to change config to default. (chests in dungeon are basically full wiht items)

**Comment by Thelnfamous1** [comment]
I fixed the comments, but the actual config values are correct. You get 1 piece of armor, 1 weapon, and a chance for an artifact in every chest with dungeons loot in it.
