### ISSUE TITLE
Some mistaken item names and inappropriate hardcoded texts

### ISSUE THREAD

**Issue by ChromaPIE** [Thelnfamous1/Dungeons-Gear#52]
Left original and right fixed

- Fang of Frost | Fangs of Frost
- Shear Dagger | Sheer Dagger
- Sickle | Sickles
- Mauler | Maulers

Moreover, quite a lot of the texts in the items' tooltips seem to be hardcoded but not given a localization key getting it ready to be translated, including all of the descriptions, and some attributes. Please add support.

**Comment by Thelnfamous1** [comment]
Since the dual wield weapons are singletons, then the name should reflect that (example: “Fang” instead of “Frost”).

Localizations are being mass-added and will be implemented in the next release.
