### ISSUE TITLE
3.0.6 incompatibility with MoreVanillaWeapons 1.7.1

### ISSUE THREAD

**Issue by IdeotikTable** [Thelnfamous1/Dungeons-Gear#53]
I'm really sure the mods used to work together and a certain release, either that or it's just me having this problem, I even tested the mods alone but never work when they're added together.

**Comment by Thelnfamous1** [comment]
Can you send the log to see what happens when they are used together?

**Comment by IdeotikTable** [comment]
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/6519307/latest.log)

The newer versions of either mod is now more compatible with each other and both now work with my modpack. After checking this is because of the newer Dungeon Gears and can now work with even older mvw mods now (at least with both mvw 1.7.1/1.7.0) , basically it solved eventually but thanks for the response since I forgot to check the mods in a while.
