### ISSUE TITLE
Iron golems stop being nice after a while

### ISSUE THREAD

**Issue by Nubidubi23** [Thelnfamous1/Dungeons-Gear#54]
So i'm playing a modpack called Mineshafts & Monsters in which all guard villagers and iron golems are hostile at the start. When i use the iron golem summon artifact , it works just fine , but after a while , the golem still teleports to me and all that , but starts attacking me for some reason. Could that be a bug from this mod or is it from the pack i'm playing?

**Comment by Demenick** [comment]
Thats due to the modpack adding a relationship to villagers that can be increased by killing certain mobs. By default villagers and irongolems/guards are hostile towards you

**Comment by Nubidubi23** [comment]
Yes , but the iron golems spawned by the Iron Golem Kit are friendly at first and only become hostile if you restart the game after spawning one or unload the chunk they're in. It should be either hostile from the start or friendly until they die , not like this. Or maybe i'm wrong and that's intended , i don't know

**Comment by Thelnfamous1** [comment]
I can probably deactivate the hostile AI of the iron golem that activates when you have negative village rep for the artifact-summoned ones, but as I understand it by default in vanilla an iron golem that you or another player built won't ever attack you

**Comment by Jackiecrazy** [comment]
Perhaps the ring of seven curses (enigmatic legacy) has a similar problem?

**Comment by xrosbeast** [comment]
> Thats due to the modpack adding a relationship to villagers that can be increased by killing certain mobs. By default villagers and irongolems/guards are hostile towards you

Why would they make them hostile by default? Why not neutral?

**Comment by Thelnfamous1** [comment]
Closing because this issue has not had much inactivity, we'll be sure to tweak stuff involving summonables as we go along updating the mod
