### ISSUE TITLE
Timeout on dedicated server near King boss/Dungeon

### ISSUE THREAD

**Issue by SimonJockel** [Thelnfamous1/Dungeons-Gear#55]
I play on a friends dedicated server and always get timed out, this only appears to happen when i am near the king dungeon, if i teleport to our home it stops happening and everything runs smooth and i dont get disconnected. i added the logs from mc 
[2021-04-20-1.log.gz](https://github.com/Thelnfamous1/Dungeons-Gear/files/6349705/2021-04-20-1.log.gz)

**Comment by Thelnfamous1** [comment]
The log, as far as I can tell, does not indicate an issue on Dungeons Gear's end.
