### ISSUE TITLE
Incompatible with Epic Fight Mod

### ISSUE THREAD

**Issue by Mbyssmaw** [Thelnfamous1/Dungeons-Gear#57]
![2021-04-27_21 37 23](https://user-images.githubusercontent.com/83290301/116250992-d1b77800-a7a0-11eb-9024-6f13897c24f7.png)
![2021-04-27_21 37 30](https://user-images.githubusercontent.com/83290301/116250999-d2e8a500-a7a0-11eb-95da-fd2ffe491b22.png)
![2021-04-27_21 37 32](https://user-images.githubusercontent.com/83290301/116251003-d419d200-a7a0-11eb-891e-50fc04415af6.png)

The armor appears to be heavily deformed possible due to the custom animations from EFM, while I did just only showed the soul hood and armor items, most of the armors seem to be experiencing the same problem

**Comment by Thelnfamous1** [comment]
I'm not too sure what can be done to ensure compatibility, can you bring this up on the EFM issue tracker as well?

**Comment by Quizer9O8** [comment]
Yesssssman (creator of Epic Fight) states that your all your armors aren't compatible with their model autogeneration. which causes weird rendering issues shown in the pictures. The Ice & Fire mod used to have this too but whatever they did on their recent updates seem to have fixed the issue. I recommend contacting one of the mod authors to come up with a solution.
 
 Link to issue: https://github.com/Yesssssman/epicfightmod/issues/134

**Comment by guivnf** [comment]
Patched Dungeon Gear mod here: https://www.planetminecraft.com/data-pack/epic-fight-dungeon-gear-patch/
