### ISSUE TITLE
Item decriptions off screen

### ISSUE THREAD

**Issue by simplemath64** [Thelnfamous1/Dungeons-Gear#6]
Can't read most of the item names.

![2020-10-31_11 41 34](https://user-images.githubusercontent.com/73724640/97785844-ee6e4c80-1b7d-11eb-9b38-39c514c10ca0.png)
![2020-10-31_11 41 43](https://user-images.githubusercontent.com/73724640/97785866-0e9e0b80-1b7e-11eb-9604-7022940781ab.png)
![2020-10-31_11 41 46](https://user-images.githubusercontent.com/73724640/97785874-13fb5600-1b7e-11eb-9409-3ce8253ffcf4.png)
![2020-10-31_11 41 49](https://user-images.githubusercontent.com/73724640/97785880-16f64680-1b7e-11eb-9cfb-22980c90b452.png)

**Comment by Thelnfamous1** [comment]
This is an issue in 1.16.2 Forge that I will not fix myself. You should update to 1.16.3 Forge.

**Comment by simplemath64** [comment]
But i am in forge 1.16.3

**Comment by Thelnfamous1** [comment]
That doesn't seem right. I have tested this in 1.16.3 Forge myself and the tooltips don't run off the screen like that. Can you give my your mod version and Forge version?

**Comment by simplemath64** [comment]
Forge version is 1.16.3-forge-34.1.0 mod version 2.0.11, I'm now going to upgrade to 2.0.12

**Comment by simplemath64** [comment]
After looking it over it doesnt appear to be a problem with your mod in particular, it seems to be problem with every long named item in my game. Dont know whats causing this.
