### ISSUE TITLE
Chilling effect applies to nearby players

### ISSUE THREAD

**Issue by Kinomora** [Thelnfamous1/Dungeons-Gear#62]
https://github.com/Thelnfamous1/Dungeons-Gear/blob/8102a99d887150181cb296920990085a9520f038/src/main/java/com/infamous/dungeons_gear/enchantments/armor/ChillingEnchantment.java#L58

Can you please add a clause that excludes other players. I cannot stand near a friend that has this enchantment without constantly getting slowness and mining fatigue causing my screen to zoom in and out every second, on top of being generally annoying to have effects constantly proc'd onto me.

**Comment by Jackiecrazy** [comment]
The config option "enableAreaOfEffectOnPlayers" can turn it off.

**Comment by Jackiecrazy** [comment]
I suppose this has been resolved? Closing then.
