### ISSUE TITLE
Dual wielding crossbows causing crash/Exploding crossbows not exploding

### ISSUE THREAD

**Issue by Krampus69** [Thelnfamous1/Dungeons-Gear#68]
Hello !
So basically the dual wielding crossbow crashes when I load it with an arrow.  Also, exploding crossbows don't  work WHEN I got my mods on. It works well with just Dungeons Gear.
Here is a crash file I got when I tried the dual wielding crossbow. Removed all of my mods to see if it crashed and it still did. 
[crash-2021-05-10_05.12.17-server.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/6451083/crash-2021-05-10_05.12.17-server.txt)

Now here is my mod list where one of the mods probably has to do with the not-exploding crossbows. I'll do some testing on my side to try to find out which one.

		TreeChop-1.16.4-0.14.0.jar                        |HT's TreeChop                 |treechop                      |0.14.0              |COMMON_SET|NOSIGNATURE
		FriendlyEndermite_v1.0.3_mc1.16.5.jar             |Friendly Endermite            |friendlyendermite             |1.0.0               |COMMON_SET|NOSIGNATURE
		notenoughcrashes-3.2.0-forge.jar                  |Not Enough Crashes            |notenoughcrashes              |3.2.0               |COMMON_SET|NOSIGNATURE
		GokiStats-1.16.3-1.2.13.jar                       |Goki Stats                    |gokistats                     |1.2.13              |COMMON_SET|NOSIGNATURE
		GlobalGameRules-1.16.4-5.0.1.3.jar                |Global GameRules              |globalgamerules               |5.0.1.3             |COMMON_SET|15:a4:a3:0e:d2:f8:64:0c:a4:97:30:5f:48:ba:5f:69:f9:23:42:14:a8:5a:60:3a:b1:b1:29:1a:0a:37:3c:79
		UnionLib-1.16.5-3.3.1.jar                         |UnionLib                      |unionlib                      |3.3.1               |COMMON_SET|NOSIGNATURE
		blood-particles-1.16.3-1.0.1.jar                  |Blood Particles               |blood_particles               |1.0.1               |COMMON_SET|NOSIGNATURE
		infernal-expansion-forge-1.3.jar                  |Infernal Expansion            |infernalexp                   |Release 1.3         |COMMON_SET|NOSIGNATURE
		deadlyendphantoms-1.16.4-3.0.0.jar                |Deadly End Phantoms           |deadlyendphantoms             |3.0.0               |COMMON_SET|NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |COMMON_SET|NOSIGNATURE
		Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |COMMON_SET|NOSIGNATURE
		ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar      |Forge Endertech               |forgeendertech                |7.1.0.0             |COMMON_SET|NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |COMMON_SET|NOSIGNATURE
		citadel-1.6.2.jar                                 |Citadel                       |citadel                       |1.6.2               |COMMON_SET|NOSIGNATURE
		alexsmobs-1.10.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.10.0              |COMMON_SET|NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |COMMON_SET|NOSIGNATURE
		Bookshelf-1.16.5-10.0.7.jar                       |Bookshelf                     |bookshelf                     |10.0.7              |COMMON_SET|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Tips-1.16.5-4.0.7.jar                             |Tips                          |tips                          |4.0.7               |COMMON_SET|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.16.5.1.2.4.jar                   |Guard Villagers               |guardvillagers                |1.2.4               |COMMON_SET|NOSIGNATURE
		ProgressiveBosses-2.2.0-mc1.16.x.jar              |Progressive Bosses            |progressivebosses             |2.2.0               |COMMON_SET|NOSIGNATURE
		SnowRealMagic-1.16.4-2.5.6.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.5.6               |COMMON_SET|NOSIGNATURE
		carryon-1.16.5-1.15.3.13.jar                      |Carry On                      |carryon                       |1.15.3.13           |COMMON_SET|8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		Paraglider-1.16.2-1.3.1.0.jar                     |Paraglider                    |paraglider                    |1.3.1.0             |COMMON_SET|NOSIGNATURE
		betterendforge-1.16.4-1.5.1.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.5.1        |COMMON_SET|NOSIGNATURE
		structure_gel-1.16.5-1.7.6.jar                    |Structure Gel API             |structure_gel                 |1.7.6               |COMMON_SET|NOSIGNATURE
		TenshiLib-1.16.3-1.3.0.jar                        |TenshiLib                     |tenshilib                     |1.16.3-1.3.0        |COMMON_SET|NOSIGNATURE
		cleancut-mc1.16-2.2-forge.jar                     |Clean Cut                     |cleancut                      |2.2                 |COMMON_SET|NOSIGNATURE
		repurposed_structures-1.16.5-2.6.6-forge.jar      |Repurposed Structures         |repurposed_structures         |1.16.5-2.6.6-forge  |COMMON_SET|NOSIGNATURE
		AmbientSounds_v3.1.6_mc1.16.5.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |COMMON_SET|NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.465-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.463   |COMMON_SET|NOSIGNATURE
		projectvibrantjourneys-1.16.5-3.0.1.jar           |Project: Vibrant Journeys     |projectvibrantjourneys        |1.16.5-3.0.1        |COMMON_SET|NOSIGNATURE
		EndRemastered-R36.jar                             |End Remastered 3.6            |endrem                        |1.16.3              |COMMON_SET|NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |COMMON_SET|NOSIGNATURE
		ChunkAnimator-1.16.5-1.2.3.jar                    |Chunk Animator                |chunkanimator                 |1.16.5-1.2.3        |COMMON_SET|NOSIGNATURE
		dungeons_plus-1.16.5-1.1.4.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.4               |COMMON_SET|NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.2.jar                     |Spawner Fix                   |sf                            |1.0.0.2             |COMMON_SET|NOSIGNATURE
		CNB-1.16.3_5-1.2.11.jar                           |Creatures and Beasts          |cnb                           |1.2.11              |COMMON_SET|NOSIGNATURE
		randomenchants-4.0.6.jar                          |Random Enchants               |randomenchants                |4.0.6               |COMMON_SET|NOSIGNATURE
		Patchouli-1.16.4-50.jar                           |Patchouli                     |patchouli                     |1.16.4-50           |COMMON_SET|NOSIGNATURE
		antiquewaystones-1.2.jar                          |Antique Waystones             |antiquewaystones              |1.2                 |COMMON_SET|NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-4.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |COMMON_SET|NOSIGNATURE
		architectury-1.10.139-forge.jar                   |Architectury                  |architectury                  |1.10.139            |COMMON_SET|NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |COMMON_SET|NOSIGNATURE
		kotlin_libraries-1.0-5.jar                        |Kotlin Libraries              |kotlin_libraries              |1.0-5               |COMMON_SET|NOSIGNATURE
		ItemPhysic_v1.4.18_mc1.16.5.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |COMMON_SET|NOSIGNATURE
		cloth-config-4.11.19-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.19             |COMMON_SET|NOSIGNATURE
		smallships-1.16.5-1.3.0.jar                       |Small Ships Mod               |smallships                    |1.3.0               |COMMON_SET|NOSIGNATURE
		Scaling-Health-Mod-1.16.5.jar                     |Scaling Health                |scalinghealth                 |4.0.5+5             |COMMON_SET|NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |COMMON_SET|NOSIGNATURE
		Disenchanting-forge-1.16.5-1.7.0.jar              |Disenchanting                 |disenchanting                 |1.6.0               |COMMON_SET|NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.3.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.3        |COMMON_SET|NOSIGNATURE
		geckolib-forge-1.16.5-3.0.31.jar                  |GeckoLib                      |geckolib3                     |3.0.31              |COMMON_SET|NOSIGNATURE
		NekosEnchantedBooks-1.16-1.2.0.jar                |Neko’s Enchanted Books        |nebs                          |1.2.0               |COMMON_SET|NOSIGNATURE
		dungeons_gear-1.16.4-3.0.7.jar                    |Dungeons Gear                 |dungeons_gear                 |3.0.7               |COMMON_SET|NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |COMMON_SET|NOSIGNATURE
		Kiwi-1.16.5-3.4.2.jar                             |Kiwi                          |kiwi                          |3.4.2               |COMMON_SET|NOSIGNATURE
		mowziesmobs-1.5.16.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.16              |COMMON_SET|NOSIGNATURE
		Ma-Enchants-1.16.3-3.5.0.jar                      |Ma Enchants                   |ma-enchants                   |1.16.3-3.5.0        |COMMON_SET|NOSIGNATURE
		XPFromHarvest-1.16.3-1.2.1.jar                    |XP From Harvest               |xpfromharvest                 |1.2.1               |COMMON_SET|NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |COMMON_SET|NOSIGNATURE
		Bountiful+Baubles+FORGE-1.16.3-0.0.2.jar          |Bountiful Baubles             |bountifulbaubles              |NONE                |COMMON_SET|NOSIGNATURE
		jei-1.16.5-7.6.1.75.jar                           |Just Enough Items             |jei                           |7.6.1.75            |COMMON_SET|NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |COMMON_SET|NOSIGNATURE
		dungeons_mobs-1.16.4-1.0.3.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.0.3               |COMMON_SET|NOSIGNATURE
		abnormals_core-1.16.5-3.1.1.jar                   |Abnormals Core                |abnormals_core                |3.1.1               |COMMON_SET|NOSIGNATURE
		Bayou-Blues-1.16.5-1.0.4.jar                      |Bayou Blues                   |bayou_blues                   |1.16.5-1.0.4        |COMMON_SET|NOSIGNATURE
		goblintraders-1.3.1-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.3.1               |COMMON_SET|NOSIGNATURE
		InvMove-1.16.3-0.4.6.jar                          |InvMove                       |invmove                       |0.4.6               |COMMON_SET|NOSIGNATURE
		Better-Badlands-1.16.5-2.0.3.jar                  |Better Badlands               |better_badlands               |1.16.5-2.0.3        |COMMON_SET|NOSIGNATURE
		Waystones_1.16.5-7.4.0.jar                        |Waystones                     |waystones                     |7.4.0               |COMMON_SET|NOSIGNATURE
		BetterPortals-1.16.4-0.3.2.jar                    |YUNG's Better Portals         |betterportals                 |1.16.4-0.3.2        |COMMON_SET|NOSIGNATURE
		Fallingleaves-1.16.4-1.0.2.jar                    |Falling Leaves                |fallingleaves                 |1.0.2               |COMMON_SET|NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |COMMON_SET|NOSIGNATURE
		tumbleweed-1.16-0.4.9.jar                         |Tumbleweed                    |tumbleweed                    |1.16-0.4.9          |COMMON_SET|NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |COMMON_SET|NOSIGNATURE
		upstream-1.0.jar                                  |Upstream                      |upstream                      |1.0                 |COMMON_SET|NOSIGNATURE
		champions-forge-1.16.5-2.0.1.5.jar                |Champions                     |champions                     |1.16.5-2.0.1.5      |COMMON_SET|NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |COMMON_SET|NOSIGNATURE
		CrockPot-1.16.3-1.4.0-release.jar                 |Crock Pot                     |crockpot                      |1.4.0-release       |COMMON_SET|NOSIGNATURE
		RealisticTorches-1.16.5-3.1.2.jar                 |Realistic Torches             |realistictorches              |1.16.5-3.1.2        |COMMON_SET|NOSIGNATURE
		iceandfire-2.1.6-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.6-1.16.4        |COMMON_SET|NOSIGNATURE
		walljump-forge-1.16.4-1.3.7.jar                   |Wall-Jump!                    |walljump                      |1.16.4-1.3.7        |COMMON_SET|NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.252.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.252           |COMMON_SET|NOSIGNATURE
		firstaid-1.9.6-BETA.jar                           |First Aid                     |firstaid                      |1.9.6-BETA          |COMMON_SET|NOSIGNATURE
		forge-1.16.5-36.1.4-universal.jar                 |Forge                         |forge                         |36.1.4              |COMMON_SET|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		notreepunching-forge-1.16.5-4.1.2.jar             |No Tree Punching              |notreepunching                |4.1.2               |COMMON_SET|NOSIGNATURE
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |COMMON_SET|NOSIGNATURE
		Extractures(v1.2)_1.16.4.jar                      |extractures                   |extractures                   |1.2                 |COMMON_SET|NOSIGNATURE
		subwild-1.2.1.jar                                 |Subterranean Wilderness       |subwild                       |1.2.1               |COMMON_SET|NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |COMMON_SET|b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		infernalmobs-1.16.2.1.jar                         |Infernal Mobs                 |infernalmobs                  |1.16.2.1            |COMMON_SET|NOSIGNATURE
		antiqueatlas-5.4.4-forge.jar                      |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |COMMON_SET|NOSIGNATURE
		dungeonsarise1.16.5-1.2.72a.jar                   |Dungeons Arise                |dungeons_arise                |1.2.72a             |COMMON_SET|NOSIGNATURE
		forge-1.16.5-36.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |COMMON_SET|NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |COMMON_SET|NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.3.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.3               |COMMON_SET|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |COMMON_SET|NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |COMMON_SET|NOSIGNATURE
		Silent-Lib-1.16.5.jar                             |Silent Lib                    |silentlib                     |4.9.1+64            |COMMON_SET|NOSIGNATURE
		CreativeCore_v2.1.0_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |COMMON_SET|NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |COMMON_SET|NOSIGNATURE
		atmospheric-1.16.5-3.1.0.jar                      |Atmospheric                   |atmospheric                   |3.1.0               |COMMON_SET|NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |COMMON_SET|NOSIGNATURE
		savageandravage-1.16.5-3.1.0.jar                  |Savage & Ravage               |savageandravage               |3.1.0               |COMMON_SET|NOSIGNATURE
		diet-forge-1.16.5-0.27.jar                        |Diet                          |diet                          |1.16.5-0.27         |COMMON_SET|NOSIGNATURE
		carrotslib-mc1.16.5-3.0b5.jar                     |Carrots Lib                   |carrots                       |3.0b5               |COMMON_SET|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |COMMON_SET|NOSIGNATURE
		Quark-r2.4-310.jar                                |Quark                         |quark                         |r2.4-310            |COMMON_SET|NOSIGNATURE
		charm-forge-1.16.5-2.3.2.jar                      |Charm                         |charm                         |2.3.2               |COMMON_SET|NOSIGNATURE
		performant-1.16.2-5-3.55m.jar                     |Performant                    |performant                    |3.40m               |COMMON_SET|NOSIGNATURE
		ToughAsNails-1.16.5-4.0.1.23-universal.jar        |Tough As Nails                |toughasnails                  |1.16.5-4.0.1.15     |COMMON_SET|NOSIGNATURE
		survivaloverhaul-1.16.5-0.4.1b.jar                |Survival Overhaul             |survivaloverhaul              |1.16.5-0.4.1b       |COMMON_SET|NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |COMMON_SET|NOSIGNATURE
		eidolon-0.2.7.jar                                 |Eidolon                       |eidolon                       |0.2.7               |COMMON_SET|NOSIGNATURE
		relics-0.1.13.jar                                 |Relics                        |relics                        |0.1.13              |COMMON_SET|NOSIGNATURE
		CuriosQuarkOBP-1.16.5-1.0.2.jar                   |Curios Quark Oddities Backpack|curiosquarkobp                |1.0.2               |COMMON_SET|NOSIGNATURE
		Artifacts-1.16.5-2.8.4.jar                        |Artifacts                     |artifacts                     |1.16.5-2.8.4        |COMMON_SET|NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |COMMON_SET|NOSIGNATURE
		globaldataandresourcepacks-1.16.4-1.7.4.jar       |Global Data- & Resourcepacks  |globaldataandresourcepacks    |1.16.4-1.7.3        |COMMON_SET|NOSIGNATURE
		tiered-1.16.5-1.2.2-forge-beta.jar                |Tiered                        |tiered                        |1.16.5-1.2.2-forge-b|COMMON_SET|NOSIGNATURE
		odyssey.jar                                       |Odyssey Structures            |odyssey_structures            |1.0.0               |COMMON_SET|NOSIGNATURE
		hunterillager-1.16.4-1.2.2.jar                    |HunterIllager                 |hunterillager                 |1.16.4-1.2.2        |COMMON_SET|NOSIGNATURE
		enhancedcelestials-1.0.4-1.16.4.jar               |Enhanced Celestials           |enhancedcelestials            |1.0.4-1.16.4        |COMMON_SET|NOSIGNATURE
		ImprovedMobs-1.16.3-1.7.3.jar                     |Improved Mobs Mod             |improvedmobs                  |1.16.3-1.7.3        |COMMON_SET|NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v1b.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v1b          |COMMON_SET|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		betterfoliage-1.1.1.jar                           |Better Foliage                |betterfoliage                 |1.1.1               |COMMON_SET|NOSIGNATURE
		xptome-1.16.5-v2.1.jar                            |XP Tome                       |xpbook                        |v2.1                |COMMON_SET|NOSIGNATURE

**Comment by Thelnfamous1** [comment]
The crash says CrossbowItem#hasAmmo is being called instead of AbstractDungeonsCrossbowItem#hasAmmo like it should, so on my end I just prefixed the hasAmmo calls with AbstractDungeonsCrossbowItem so there's no confusion during execution

**Comment by Krampus69** [comment]
Hello hello so I've been testing on my side and the error with the explosive crossbows is due to another mod : Hunter Illager.
https://www.curseforge.com/minecraft/mc-mods/hunterillager

This is probably mostly due to the quiver which is a new item that can store arrows
![image](https://user-images.githubusercontent.com/81943963/118037687-78d60b00-b36e-11eb-9cb6-7bfec3c49d4c.png)

There is no way for me to actually understand how Hunter Illager works and modify arrows but it's really changing something regarding the ammo, because the exploding crossbow doesn't explode even when I don't have any quiver in my inventory.

I'm trying to contact the hunter illager author but its github is not working properly, I don't know if this info can help you understand a bit better why I'm having the explosion issue, or even if you can fix it on your hand, I'll come back to you if I get an answer from the author.

About the dual wielding crossbow tho I don't have any clue, but what TheInfamous1 said might a good hint on what's causing the crashes. Thanks for your time and your help 🙏

**Comment by Jackiecrazy** [comment]
How recent was this change? I can't find any code related to the quiver in their repository, and it's just been updated 22 days ago.

**Comment by Krampus69** [comment]
I can't tell but the author told me he used Mixin for this mod which probably means it is pretty old.
Here is his answer regarding this arrow problem :
![image](https://user-images.githubusercontent.com/81943963/118089404-946dff80-b3c8-11eb-986e-85643025c215.png)

This morning, the mod got updated. The quiver has been removed. Now I can tell you one thing : The exploding crossbow works again. So, I think that was the right guess. Anyways, that is fixed.

The only issue now is that dual wielding crossbow thing that may be fixed with "AbstractDungeonsCrossbowItem" prefix 👍
