### ISSUE TITLE
[Compatibility] YUNGs-Better-Strongholds: Loot table integration

### ISSUE THREAD

**Issue by Quizer9O8** [Thelnfamous1/Dungeons-Gear#70]
Would it be possible to integrate Dungeons gear armor into the chests/barrels in the strongholds of YUNGs-Better-Strongholds as another way of obtaining them?

**Comment by Jackiecrazy** [comment]
There is a list of config options to customize loot tables where the dungeons items show up. Crafttweaker and tellme can dump loot tables.

**Comment by Jackiecrazy** [comment]
for reference, they are:
betterstrongholds:chests/armoury
betterstrongholds:chests/cmd_yung
betterstrongholds:chests/common
betterstrongholds:chests/crypt
betterstrongholds:chests/grand_library
betterstrongholds:chests/library_md
betterstrongholds:chests/mess
betterstrongholds:chests/prison_lg
betterstrongholds:chests/trap
betterstrongholds:chests/treasure
