### ISSUE TITLE
[FEATURE REQUEST] Individually disable/enable enchantments, and if Treasure Enchant only or not

### ISSUE THREAD

**Issue by Reshirou** [Thelnfamous1/Dungeons-Gear#71]
Full enable/disable either via making the enchantment unobtainable in survival, or completely removing it,
and true/false whether the enchantment is Treasure only, meaning it can only be obtained via enchanted books in treasure chests and not in the enchanting table (good for strong rare enchantments like ones that give more emeralds or strongly increase EXP)

**Comment by Thelnfamous1** [comment]
Will be implementing some kind of blacklist for this soon

**Comment by Thelnfamous1** [comment]
Added in latest release
