### ISSUE TITLE
[SOFT INCOMPATIBILITY] Disabling enchantments for non-Dungeons gear doesn't work with Quark's matrix enchanting

### ISSUE THREAD

**Issue by Reshirou** [Thelnfamous1/Dungeons-Gear#72]
Quark's Matrix Enchanting will still spawn in Dungeons enchantments even with enableEnchantsOnNonDungeonsGear = false

Tested with nothing but Quark (Oddities) and Dungeons Gear, with enableEnchantsOnNonDungeonsGear = false

EDIT: You can of course manually blacklist each enchantment in quark's config, but then they can't even be applied to Dungeons Gear themselves, without enchanted book versions

**Comment by Thelnfamous1** [comment]
Would an enchantment blacklist on our end solve your issue? We've been getting a lot of requests for an enchantment blacklist and I will soon attempt to implement one.

**Comment by Thelnfamous1** [comment]
Closing because Quark's Matrix Enchanting changes the enchanting system far too much to add compatibility in a reasonable and timely manner on our end
