### ISSUE TITLE
Encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by zuio1234** [Thelnfamous1/Dungeons-Gear#73]
[crash-2021-05-18_20.49.53-fml.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/6503653/crash-2021-05-18_20.49.53-fml.txt)

**Comment by zuio1234** [comment]
Help if someone know what issue is

**Comment by Thelnfamous1** [comment]
Does this happen when you play the mod by itself?

**Comment by zuio1234** [comment]
no when its loading into minecraft

**Comment by Thelnfamous1** [comment]
so you cannot play the mod at all?

**Comment by zuio1234** [comment]
yes i can

**Comment by zuio1234** [comment]
maybe is then some conflict with some mod

**Comment by Thelnfamous1** [comment]
Most likely yes. I would advise doing the following:
Taking out half of your mods
Attempting to load the game
If it loads, the problematic mod is in the group that you removed
If it doesn't load, the problematic mod is in the group you currently have left

Keep splitting each group and testing until you can find the problematic mod and then report back

**Comment by zuio1234** [comment]
I tried separate with every mods and its working but when i am using it in modpack with all this mods i get error so i dont know what to do

**Comment by Thelnfamous1** [comment]
Wait so you can run all the mods separately with this mod and they work fine? What modpack are you using?

**Comment by zuio1234** [comment]
i have valhelsia modpack but i added some more mods

**Comment by zuio1234** [comment]
[crash-2021-05-19_00.24.46-fml.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/6504817/crash-2021-05-19_00.24.46-fml.txt)
i separate mods that i put in valhelsia and tried to load them with dungeons gear and i get this error, now i tried separate those mods and it works just fine only when those mods are together i get error

**Comment by Jackiecrazy** [comment]
It looks like someone... deleted the bow model properties? That sounds like a bad idea.

**Comment by Thelnfamous1** [comment]
Very bad. Whichever mod is doing that, I'd like to hear their reasoning behind that.

**Comment by zuio1234** [comment]
I think i found a problem it was The gems project mod , now its working again when i removed it

**Comment by Thelnfamous1** [comment]
Let them know about this issue, I can't seem to find the problem in their mod's code
