### ISSUE TITLE
Dual crossbows crash the server when drawn

### ISSUE THREAD

**Issue by Demmens** [Thelnfamous1/Dungeons-Gear#78]
As title says. Playing on a multiplayer server and the server crashed twice when I drew the crossbow back

**Comment by Demmens** [comment]
The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access method net.minecraft.item.CrossbowItem.func_220021_a(Lnet/minecraft/entity/LivingEntity;Lnet/minecraft/item/ItemStack;)Z from class com.infamous.dungeons_gear.ranged.crossbows.DualCrossbowItem
Exit Code: -1

**Comment by Thelnfamous1** [comment]
You should be using the latest version, which fixed this

**Comment by Demmens** [comment]
apologies, my curseforge isn't showing that there's an update available so I assumed I was on the latest.
