### ISSUE TITLE
Able to hit with longer weapons through walls

### ISSUE THREAD

**Issue by zEpiixz** [Thelnfamous1/Dungeons-Gear#79]
If you use a glaive for example i can hit mobs behind walls.  Doesnt seem very intendet.

**Comment by Thelnfamous1** [comment]
Can you describe more how you are hitting the mobs behind walls? Is it through a non-standard block that has openings in it, like a fence block?

**Comment by Thelnfamous1** [comment]
our current implementation of attack reach should be working just fine now, feel free to reopen this issue if it persists.
