### ISSUE TITLE
Crash w/ Extra Golems

### ISSUE THREAD

**Issue by WenXin20** [Thelnfamous1/Dungeons-Gear#8]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Dungeons' Gear v1.1.7`
[`Extra Golems v10.2.3`](https://www.curseforge.com/minecraft/mc-mods/extra-golems)
[`Quark r2.1-245`](https://www.curseforge.com/minecraft/mc-mods/quark)

My game crashed after a Quark Cyan Slimey Golem died after fighting some mobs in the nether. Extra Golems has addon compat for Quark, but when the Cyan Slimey Golem died and tried to split into two (like slimes), the game crashed. .
The golem can be spawned in using the Golem Head and the Cyan Slime Block, placed in a shape similar to the Iron Golem. Or `/summon`.
[Crash Report](https://gist.github.com/WenXin20/b1a3a743deafaf543b176fadb6cae5c5)

**Comment by Thelnfamous1** [comment]
1.15.2 is technically a version no longer supported by me, but I am planning to backport the entirety of the 1.16.3 version to 1.15.2. I would wait until that backport comes and recheck to see if that error persists.

**Comment by WenXin20** [comment]
Alright, thanks.

**Comment by Thelnfamous1** [comment]
An updated 1.15.2 version has been released. The issue should not persist with it, so I will be closing this thread, but feel free to make another comment here if it persists.
