### ISSUE TITLE
Incompatibility with Biomes O' Plenty on Mohist server 1.16.5

### ISSUE THREAD

**Issue by Laik0n** [Thelnfamous1/Dungeons-Gear#80]
I do not speak English well, and I will try to state my problem. Biomes O 'Plenty does not work with the new version of Dungeons-Gear,
but version 3.0.7 works well. Maybe some new features prevent the new version from working? I will be offended to play without new models and fixes.
[2021-05-24-1.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/6531158/2021-05-24-1.log)

**Comment by Thelnfamous1** [comment]
@Jackiecrazy AOE cloud mixin again

**Comment by Laik0n** [comment]
> @Jackiecrazy AOE облачный миксин снова

I do not really understand, can I have a more detailed answer? What do I need to do again?

**Comment by Thelnfamous1** [comment]
That wasn't directed towards you, I am notifying the other developer who works on this mod that there is another conflict happening with something they worked on.

**Comment by Jackiecrazy** [comment]
I pushed the necessary changes to master already.
