### ISSUE TITLE
Game freezes when overleveled Deflect enchantment tries to block arrow from crossbow with Piercing enchantment

### ISSUE THREAD

**Issue by Aiva418** [Thelnfamous1/Dungeons-Gear#81]
I was playing around on my survival world and noticed that whenver a certain pillager with an enchanted crossbow shot at me, the game would freeze. I tested it a few more times with the same pillager, and eventually I was able to kill it and (by a stroke of luck) obtain its crossbow, which was revealed to only have Piercing 1. I have Deflect 6 on my boots, so I'm wondering if this problem has to do with the way projectiles are blocked?
I should clarify that this doesn't happen if the armor is enchanted with Deflect 3. I have only reproduced it with Deflect enchantments above 3 (which is allowed if Apotheosis is installed).

I'm playing Enigmatica 6, but I also have dungeons_gear-1.16.5-3.0.15.
I also tested this on a fresh installation of Forge with only Dungeons Gear, and the same thing happened.

The game never crashed, only froze, so there is no crash log. I also checked debug.log and latest.log and nothing came up at or around the time of the game freezing.

**Comment by Jackiecrazy** [comment]
Do you have access to visualVM? You can check hanging processes with that. The game will also automatically shut down after 60 seconds of freezing if you're on a server. I'll look over this one.

**Comment by Aiva418** [comment]
I'm not sure what visualVM is. And I've been playing exclusively in singleplayer.

**Comment by Jackiecrazy** [comment]
This should be fixed with .16. Piercing doesn't play nice with stuff that tries to deflect it, looks like. The vanilla shield doesn't block it either, so I've just set piercing arrows to ignore deflect.
