### ISSUE TITLE
Rushdown enchantment crashes server

### ISSUE THREAD

**Issue by Anarchyfiend** [Thelnfamous1/Dungeons-Gear#82]
Recently members of my minecraft server have gotten ahold of the either incomplete or broken rushdown enchantment, and just by having an enchanted book of it it proceeded to cause the entire server to crash which was only resolved when we edited his player data to delete the book from his inventory.  Just wanted to log it here in case theres a way to prevent it from happening in the future or if you're unaware.

**Comment by Jackiecrazy** [comment]
A crash log would be appreciated.

**Comment by Thelnfamous1** [comment]
If there is no crash log, we cannot help you. Regardless, Rushdown should already be working completely fine by next release.
