### ISSUE TITLE
Crashing on Mohist server

### ISSUE THREAD

**Issue by mattiTD** [Thelnfamous1/Dungeons-Gear#84]
Try to starting dungeons_gear-1.16.5-3.0.15.jar on mohist server crash it and wont start.

[latest mohist log.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/6597035/latest.mohist.log.txt)

**Comment by Laik0n** [comment]
I have already posed such a question. Only the mod did not work for me together with Biomes O 'Plently.

**Comment by Jackiecrazy** [comment]
This should be fixed with .16
