### ISSUE TITLE
Burning Enchantment Kills Friendly Entities

### ISSUE THREAD

**Issue by 704Prod** [Thelnfamous1/Dungeons-Gear#86]
Is there a way to stop the burning enchantment from killing tamed, neutral and passive animals? It sucks when I have to take off my armor just to enter my house because I'll kill my girlfriend's tamed ocelot. Same goes for anyone else's essentially harmless pet

**Comment by Jackiecrazy** [comment]
Pretty sure this option exists in the config. Look for "effectTargetBlacklist" in the latest couple of versions.
