### ISSUE TITLE
Crash when running forge 1.16.5 36.1.25

### ISSUE THREAD

**Issue by Potatoes9411** [Thelnfamous1/Dungeons-Gear#87]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 6/6/21 12:11 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$16533/586902155.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$14342/1295062300.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.25.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$456/917131986.call(Unknown Source) [forge-1.16.5-36.1.25.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.infamous.dungeons_gear.items.VanillaItemModelProperties.<init>(VanillaItemModelProperties.java:19) ~[?:3.0.15] {re:classloading}
-- MOD dungeons_gear --
Details:
	Mod File: dungeons_gear-1.16.5-3.0.15.jar
	Failure message: Dungeons Gear (dungeons_gear) encountered an error during the sided_setup event phase
		java.lang.NullPointerException: null
	Mod Version: 3.0.15
	Mod Issue URL: http://my.issue.tracker/
	Exception message: java.lang.NullPointerException
Stacktrace:
	at com.infamous.dungeons_gear.items.VanillaItemModelProperties.<init>(VanillaItemModelProperties.java:19) ~[?:3.0.15] {re:classloading}
	at com.infamous.dungeons_gear.DungeonsGear.doClientStuff(DungeonsGear.java:101) ~[?:3.0.15] {re:classloading}
	at com.infamous.dungeons_gear.DungeonsGear$$Lambda$9378/1549931736.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2913/1729992636.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2550/1183774942.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3157/633103787.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4613726656 bytes (4399 MB) / 7516192768 bytes (7168 MB) up to 7516192768 bytes (7168 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.25.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.25.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.25.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.25.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.25.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.25
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		SaveMyStronghold-1.16.4-1.0.jar                   |Save My Stronghold!           |savemystronghold              |1.16.4-1.0          |ENQUEUE_IM|Manifest: NOSIGNATURE
		mowziesmobs-1.5.17.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.17              |ENQUEUE_IM|Manifest: NOSIGNATURE
		vanillaexcavators-1.16.4-2.2.1.jar                |Vanilla Excavators            |vanillaexcavators             |2.2.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		SwordsMod+-+2.0.2.jar                             |Swords Mod                    |rswords                       |1.16.3 - 1.16.5 - 2.|ENQUEUE_IM|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.0.103.jar                          |Just Enough Items             |jei                           |7.7.0.103           |ENQUEUE_IM|Manifest: NOSIGNATURE
		WarpedNetherite_1.0.jar                           |Cracked Netherite             |cracked_netherite             |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		dungeons_mobs-1.16.5-1.0.5.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.0.5               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-windows-1.0.3-mc1.16.5.jar                    |Macaw's Windows               |mcwwindows                    |1.0.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		KleeSlabs_1.16.5-9.2.1.jar                        |KleeSlabs                     |kleeslabs                     |9.2.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		BlockArmor-1.16.5-2.6.2.jar                       |Block Armor                   |blockarmor                    |2.6.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151|ENQUEUE_IM|Manifest: NOSIGNATURE
		ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar      |Forge Endertech               |forgeendertech                |7.1.0.0             |ENQUEUE_IM|Manifest: NOSIGNATURE
		WeaponThrow-1.16.4-4.2.jar                        |Weapon Throw                  |weaponthrow                   |1.16.4-4.2          |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-paintings-1.0.1-mc1.16.5.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Clumps-6.0.0.24.jar                               |Clumps                        |clumps                        |6.0.0.24            |ENQUEUE_IM|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.2beta3.jar                  |Journeymap                    |journeymap                    |5.7.2beta3          |ENQUEUE_IM|Manifest: NOSIGNATURE
		citadel-1.6.3.jar                                 |Citadel                       |citadel                       |1.6.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		NamePain-1.3.1+Forge-1.16.x.jar                   |Name Pain                     |namepain                      |1.3.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |ENQUEUE_IM|Manifest: NOSIGNATURE
		netheritehorsearmor-1.7.jar                       |Netherite Horse Armor Mod     |netheritehorsearmor           |1.7                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		AdHooks-1.16.4-6.1.5.0-build.0124.jar             |Advanced Hook Launchers       |adhooks                       |6.1.5.0             |ENQUEUE_IM|Manifest: NOSIGNATURE
		endercrop-1.16.5-1.6.0-beta.jar                   |Ender Crop                    |endercrop                     |1.16.5-1.6.0-beta   |ENQUEUE_IM|Manifest: NOSIGNATURE
		damage-tint-forge-1.16.5-1.0.1.jar                |Damage tint                   |damagetint                    |1.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-doors-1.0.2-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		sworddisplay-1.16.5-1.2.0.jar                     |Sword Displays                |sworddisplay                  |1.16.5-1.2.0        |ENQUEUE_IM|Manifest: NOSIGNATURE
		iceandfire-2.1.6-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.6-1.16.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |ENQUEUE_IM|Manifest: NOSIGNATURE
		walljump-forge-1.16.4-1.3.7.jar                   |Wall-Jump!                    |walljump                      |1.16.4-1.3.7        |ENQUEUE_IM|Manifest: NOSIGNATURE
		projectdawn-1.16.4-1.1.1.jar                      |Dawn to Dusk                  |projectdawn                   |1.16.4-1.1.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.4.0.jar                       |iChunUtil                     |ichunutil                     |10.4.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.3.13.jar                      |Carry On                      |carryon                       |1.15.3.13           |ENQUEUE_IM|Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		gems-1.16.5-1.7.3.jar                             |The Gems Project              |gems                          |1.16.5-1.7.3        |ENQUEUE_IM|Manifest: NOSIGNATURE
		ThrowableExplosives-1.16.5-1.1.0.jar              |Throwable Explosives          |throwableexplosives           |1.1.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.16.5-36.1.25-universal.jar                |Forge                         |forge                         |36.1.25             |ENQUEUE_IM|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		netherite-plus-mod-1.4.5-1.16.5-forge.jar         |Netherite Plus                |netherite_plus                |1.4.5-1.16.5        |ENQUEUE_IM|Manifest: NOSIGNATURE
		betterendforge-1.16.4-1.6.0.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.6.0        |ENQUEUE_IM|Manifest: NOSIGNATURE
		Upgraded+Netherite+1.16.5+-+1.9.5.jar             |Upgraded Netherite            |upgradednetherite             |1.7.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		emotecraft-for-MC1.16.5-2.0.1-forge.jar           |Emotecraft                    |emotecraft                    |2.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |ENQUEUE_IM|Manifest: NOSIGNATURE
		ironchest-1.16.4-11.2.10 (1).jar                  |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |ENQUEUE_IM|Manifest: NOSIGNATURE
		Apples++1.16.5+v2.4.jar                           |Apples+                       |apples                        |2.4                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		UselessSword-1.16.5-V1.3.3.jar                    |Useless Sword                 |useless_sword                 |1.3.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		dungeons_1.8_mc1.16.5.jar                         |Minecraft Dungeons            |duneons                       |1.8 Flames of  the N|ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.16.5-36.1.25-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |ENQUEUE_IM|Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.0.4.171.jar                   |Tinkers' Construct            |tconstruct                    |3.0.4.171           |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-bridges-1.0.5-mc1.16.5-4.jar                  |Macaw's Bridges               |mcwbridges                    |1.0.5               |ENQUEUE_IM|Manifest: NOSIGNATURE
		customizableelytra-1.16.4-1.4.4.jar               |Customizable Elytra           |customizableelytra            |1.16.4-1.4.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		morevanillalib-1.16.4-1.4.0.jar                   |MoreVanillaLib                |morevanillalib                |1.4.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		morevanillatools-1.16.4-2.2.0.jar                 |MoreVanillaTools              |morevanillatools              |2.2.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		1.16.5-enchantedgoldenapplecrafting-1.0 (1).jar   |Enchanted Golden Apple Craftin|enchantedgoldenapplecrafting  |1.0                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |ENQUEUE_IM|Manifest: NOSIGNATURE
		CreativeCore_v2.2.0_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.2-mc1.16.5.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-fences-1.0.0-mc1.16.5.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		AdLods-1.16.4-4.1.5.1-build.0118.jar              |Large Ore Deposits            |adlods                        |4.1.5.1             |ENQUEUE_IM|Manifest: NOSIGNATURE
		hole_filler_mod_1.2.4.1-mc_1.16.x-forge.jar       |Hole Filler Mod               |hole_filler_mod               |1.2.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |ENQUEUE_IM|Manifest: NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.103.jar                         |Mantle                        |mantle                        |1.6.103             |ENQUEUE_IM|Manifest: NOSIGNATURE
		EasyEmerald-Forge-1.16.5-1.0.25.jar               |Easy Emerald                  |easy_emerald                  |1.0.25              |ENQUEUE_IM|Manifest: NOSIGNATURE
		AppleTreesRev-Forge-1.16.5-v1.3.jar               |Apple Trees Revived           |appletreesrev                 |1.3                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Quark-r2.4-312.jar                                |Quark                         |quark                         |r2.4-312            |ENQUEUE_IM|Manifest: NOSIGNATURE
		extragolems-11.3.1.jar                            |Extra Golems                  |golems                        |11.3.1              |ENQUEUE_IM|Manifest: NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |ENQUEUE_IM|Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.16.4-1.4.0.jar          |Better Third Person           |betterthirdperson             |1.4.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		vanillahammers-1.16.4-2.2.0.jar                   |Vanilla Hammers               |vanillahammers                |2.2.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Gobber2-Forge-1.16.5-2.3.50.jar                   |Gobber 2                      |gobber2                       |2.3.48              |ENQUEUE_IM|Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.1.jar                  |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.1          |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-roofs-2.0.1-mc1.16.5-4.jar                    |Macaw's Roofs                 |mcwroofs                      |2.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		cfm-7.0.0pre21-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre21         |ENQUEUE_IM|Manifest: NOSIGNATURE
		architectury-1.17.20-forge.jar                    |Architectury                  |architectury                  |1.17.20             |ENQUEUE_IM|Manifest: NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		BackTools-1.16.5-10.1.0.jar                       |Back Tools                    |backtools                     |10.1.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		ItemPhysic_v1.4.18_mc1.16.5.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		DamageTilt-1.16-forge-0.1.1.jar                   |DamageTilt                    |damagetilt                    |0.1.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		AdChimneys-1.16.4-6.0.10.0-build.0125.jar         |Advanced Chimneys             |adchimneys                    |6.0.10.0            |ENQUEUE_IM|Manifest: NOSIGNATURE
		the_bumblezone-1.16.5-2.2.14.jar                  |The Bumblezone                |the_bumblezone                |1.16.5-2.2.14       |ENQUEUE_IM|Manifest: NOSIGNATURE
		enchantwithmob-1.16.5-1.4.3.jar                   |Enchant With Mob              |enchantwithmob                |1.16.5-1.4.3        |ENQUEUE_IM|Manifest: NOSIGNATURE
		Japp's+apple+of+diamond+block+v1.2.jar            |Japp's Apple of diamond block |japps_apple_of_diamond_block  |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		switchbow-1.7.jar                                 |Switch-Bow                    |switchbow                     |1.7                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		chiselsandbits-0.3.4-RELEASE (1).jar              |Chisels & bits                |chiselsandbits                |NONE                |ENQUEUE_IM|Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.3.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.3        |ENQUEUE_IM|Manifest: NOSIGNATURE
		dungeons_gear-1.16.5-3.0.15.jar                   |Dungeons Gear                 |dungeons_gear                 |3.0.15              |ERROR     |Manifest: NOSIGNATURE
		Cyan+Warrior+Swords+Mod+3.1-RC1+(1.16.5).jar      |Cyan Warrior Swords Mod       |cwsr                          |3.1.0.0             |ENQUEUE_IM|Manifest: NOSIGNATURE
		xptome-1.16.5-v2.1.2.jar                          |XP Tome                       |xpbook                        |v2.1.2              |ENQUEUE_IM|Manifest: NOSIGNATURE
	Crash Report UUID: 1d5c36e1-783d-480a-9858-812b2b79377c

**Comment by Jackiecrazy** [comment]
This may be related to #73

**Comment by Potatoes9411** [comment]
its not i dont think idk
