### ISSUE TITLE
Null textures

### ISSUE THREAD

**Issue by PassiveLemon** [Thelnfamous1/Dungeons-Gear#88]
Some items are missing textures and other appear to have bugged textures.
Null are the purple black textures and the bugged ones are the super large vanilla bow texture.

Melee:
Frost Slayer - Null
Boneclub - Null
Bone Cudgel - Null
Broken Sawblade - Null
Mechanized Sawblade - Null

Ranged:
Shivering Bow - Null
Wind Bow - Bugged
Burst Gale - Bugged
Echo of the Valley - Bugged
Twisting Vine - Null
Weeping Vine - Null
Cog Crossbow - Null
Pride of the Piglins - Null

![2021-06-08_20 47 00](https://user-images.githubusercontent.com/72527881/121275479-d476b400-c89a-11eb-9499-d4032a206ee3.png)

**Comment by Jackiecrazy** [comment]
They're not done yet, and are also unobtainable in survival.
