### ISSUE TITLE
startup crash with the new 1.15 version

### ISSUE THREAD

**Issue by aycfes** [Thelnfamous1/Dungeons-Gear#9]
[crash-2020-11-05_09.31.15-client.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/5494042/crash-2020-11-05_09.31.15-client.txt)
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5494047/latest.log)
[debug.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/5494049/debug.log)
there's not much more info i can give, as far as i know, but ask if you think otherwise

**Comment by Thelnfamous1** [comment]
Only major thing I see is this: 
java.lang.NullPointerException: Registry Object not present: productivebees:sugar_cane_nest

Talk to the productive bees devs about this. I can’t point out anything wrong from the perspective of Dungeons Gear.

**Comment by Thelnfamous1** [comment]
Do you happen to know if you are playing with any mods that give you extended attack reach in any way, besides Dungeons Gear?

**Comment by aycfes** [comment]
well, there's astral sorcery, that comes to mind immediately, and one or two other might also do it (boutiful baubles, artifacts)

and i know that productive bees isn't the culprit, as even when removing it, the crash happens

**Comment by Thelnfamous1** [comment]
Astral Sorcery may be the culprit then. They are using Javascript coremods to modify attack reach, which I am also doing but with mixins instead. Since they change it before I do, my mixin fails and then the entire modloading state fails. I can’t really say as to whether or not this incompatibility could be fixed on our 1.15 versions.

**Comment by aycfes** [comment]
i see...
in that case, imma go bug hellfire about it, but wouldn't it be possible to revert that spacific feature to be like in the previous version, which caused no problems (as a config, maybe)

**Comment by Thelnfamous1** [comment]
I don't think it can be configurable, I would likely have to remove the mixin entirely and rewrite it using the old way. This whole situation is just more proof that Forge needs a standardized attack reach attribute, as Hellfire and I seem to be doing the exact same thing in a conflicting manner.

**Comment by Thelnfamous1** [comment]
I will be releasing an updated version for 1.15 that no longer uses mixin for attack reach and should be working completely separately to what Hellfire and other modders try to do with attack reach.

**Comment by aycfes** [comment]
nice ^^
once again, thank you, and sorry for the bother
feel free to message me if ya need any help, i owe ya one, and will do my best

**Comment by Thelnfamous1** [comment]
It should be up now. Thanks for bringing it up.
