### ISSUE TITLE
Mod Texture Incompatability

### ISSUE THREAD

**Issue by Big-Kuma** [Thelnfamous1/Dungeons-Gear#92]
I am on a modpack with 100+ mods so sadly I won't be able to single out which mod is causing this. However when in-game none of the armor textures seem to load in properly. They look just like a bunch of mixed-up pixels. However, when looking at yourself in the inventory, it looks fine. If anyone finds out which mod is doing this to dungeons gear, it would be great to add as an incompatible mod. Or to possibly fix it.

**Comment by Jackiecrazy** [comment]
Epic fight.

**Comment by Thelnfamous1** [comment]
At the moment epic fight mod compatibility is not being considered.
