### ISSUE TITLE
lanzar el "FinalShoutEnchantment" bloqueo el servidor o eso parece

### ISSUE THREAD

**Issue by d-rick** [Thelnfamous1/Dungeons-Gear#93]
hola mi servidor se bloqueo al usar un artefacto que lanza rayos de su mod no entiendo mucho de esto asi que dejo el crash report para que me ayude gracias

[crash report.txt](https://github.com/Thelnfamous1/Dungeons-Gear/files/6653002/crash.report.txt)

**Comment by Thelnfamous1** [comment]
@Jackiecrazy ItemUseContext is being illegally accessed during an artifact proc call?

**Comment by Jackiecrazy** [comment]
Fixed.
