### ISSUE TITLE
Corrupted Pumpking and Beacon not shooting

### ISSUE THREAD

**Issue by Explode007** [Thelnfamous1/Dungeons-Gear#95]
Yeah; that's basically it. In creative I can shoot them just fine but in survival even with 200 levels of XP i cant shoot them at all.

**Comment by Explode007** [comment]
Update: I can shoot them but they are kinda buggy

**Comment by Thelnfamous1** [comment]
Will be more consistent in the next update, which will introduce soul mechanics and avoid XP depletion.
