### ISSUE TITLE
[FEATURE REQUEST] Config overall loot chance

### ISSUE THREAD

**Issue by egshels** [Thelnfamous1/Dungeons-Gear#97]
It would be extremely helpful to be able to dictate the chance for an armor, weapon, or artifact to be able to spawn at all in loot pools of varying rarities rather than only the chance for them to be higher quality.

**Comment by Thelnfamous1** [comment]
Sure, the loot config is due for a rework.

**Comment by Thelnfamous1** [comment]
Closing, keep an eye on #105 which will include adding this
